/*    _      _ _
     /_\  __| (_)_ __  ___
    / _ \/ _` | | '  \/ -_)
   /_/ \_\__,_|_|_|_|_\___|

   register.c:
   List of dialogf formats, kept in a separate file so that they can be
   overridden by user programs.

   By Sven Sandberg

   See readme.txt for more information about Adime.
*/
#include <allegro.h>

#include "adime.h"



ADIME_BEGIN_FORMAT_LIST
   ADIME_FORMAT_BOOL
   ADIME_FORMAT_GREYBOOL
   ADIME_FORMAT_BUTTON
   ADIME_FORMAT_BUTTONROW
   ADIME_FORMAT_STRING
   ADIME_FORMAT_FILENAME
   ADIME_FORMAT_VLIST
   ADIME_FORMAT_LIST
   ADIME_FORMAT_DATAFILE
   ADIME_FORMAT_WVLIST
   ADIME_FORMAT_WLIST
   ADIME_FORMAT_WDATAFILE
   ADIME_FORMAT_DIALOGF
   ADIME_FORMAT_VDIALOGF
   ADIME_FORMAT_INT
   ADIME_FORMAT_PINT
   ADIME_FORMAT_UINT
   ADIME_FORMAT_PUINT
   ADIME_FORMAT_SHORT
   ADIME_FORMAT_PSHORT
   ADIME_FORMAT_USHORT
   ADIME_FORMAT_PUSHORT
   ADIME_FORMAT_CHAR
   ADIME_FORMAT_PCHAR
   ADIME_FORMAT_UCHAR
   ADIME_FORMAT_PUCHAR
   #ifdef ADIME_LONG_LONG
      ADIME_FORMAT_LONGLONG
      ADIME_FORMAT_PLONGLONG
      ADIME_FORMAT_ULONGLONG
      ADIME_FORMAT_PULONGLONG
   #endif
   ADIME_FORMAT_DOUBLE
   ADIME_FORMAT_PDOUBLE
   ADIME_FORMAT_FLOAT
   ADIME_FORMAT_PFLOAT
   ADIME_FORMAT_LINE
   ADIME_FORMAT_NOTHING
   ADIME_FORMAT_CHAIN
ADIME_END_FORMAT_LIST
