#
# helper makefile included from the native makefile to fill in
# possibly missing variable values.
#

# file suffixes

ifndef EXE_SUFFIX
  EXE_SUFFIX = 
endif
ifndef OBJ_SUFFIX
  OBJ_SUFFIX = .o
endif
ifndef LIB_SUFFIX
  LIB_SUFFIX = .a
endif
ifndef HTML_SUFFIX
  HTML_SUFFIX = .html
endif
ifndef INFO_SUFFIX
  INFO_SUFFIX = .info
endif
ifndef TEXI_SUFFIX
  TEXI_SUFFIX = .texi
endif
ifndef _TX_HTML_FLAG
  _TX_HTML_FLAG = -html
endif
ifndef _TX_TEXI_FLAG
  _TX_TEXI_FLAG = -texi
endif


# compiling and linking

# LINK_EXE and LINK_EXE_ALL must be defined

ifndef LINK_EXE_NOLIB
  LINK_EXE_NOLIB = $(LINK_EXE)
  LINK_EXE_NOLIB_DEPS = $(LINK_EXE_DEPS)
endif

ifndef LINK_EXE_ALL_NOLIB
  LINK_EXE_ALL_NOLIB = $(LINK_EXE_ALL)
  LINK_EXE_ALL_NOLIB_DEPS = $(LINK_EXE_ALL_DEPS)
endif


ifndef LINK_EXE_CONSOLE
  LINK_EXE_CONSOLE_DEPS = $(LINK_EXE_DEPS)
  LINK_EXE_CONSOLE = $(LINK_EXE)
endif

ifndef LINK_EXE_CONSOLE_ALL
  LINK_EXE_CONSOLE_ALL_DEPS = $(LINK_EXE_ALL_DEPS)
  LINK_EXE_CONSOLE_ALL = $(LINK_EXE_ALL)
endif

ifndef LINK_EXE_CONSOLE_NOLIB
  LINK_EXE_CONSOLE_NOLIB_DEPS = $(LINK_EXE_NOLIB_DEPS)
  LINK_EXE_CONSOLE_NOLIB = $(LINK_EXE_NOLIB)
endif

ifndef LINK_EXE_CONSOLE_ALL_NOLIB
  LINK_EXE_CONSOLE_ALL_NOLIB_DEPS = $(LINK_EXE_ALL_NOLIB_DEPS)
  LINK_EXE_CONSOLE_ALL_NOLIB = $(LINK_EXE_ALL_NOLIB)
endif
