/* Allegro datafile object indexes, produced by grabber v4.2.2, Unix */
/* Datafile: /home/kiler/mmam/data/sprites.dat */
/* Date: Tue Dec 23 13:29:41 2008 */
/* Do not hand edit! */

#define SPR_10MM_T0                      0        /* BMP  */
#define SPR_50CAL_T0                     1        /* BMP  */
#define SPR_AA0001                       2        /* BMP  */
#define SPR_AA0002                       3        /* BMP  */
#define SPR_AA0003                       4        /* BMP  */
#define SPR_AA0004                       5        /* BMP  */
#define SPR_AA0005                       6        /* BMP  */
#define SPR_AA0006                       7        /* BMP  */
#define SPR_AA0007                       8        /* BMP  */
#define SPR_AA0008                       9        /* BMP  */
#define SPR_AA0009                       10       /* BMP  */
#define SPR_AA0010                       11       /* BMP  */
#define SPR_AA0011                       12       /* BMP  */
#define SPR_AA0012                       13       /* BMP  */
#define SPR_AA0013                       14       /* BMP  */
#define SPR_AA0014                       15       /* BMP  */
#define SPR_AB0001                       16       /* BMP  */
#define SPR_AB0002                       17       /* BMP  */
#define SPR_AB0003                       18       /* BMP  */
#define SPR_AB0004                       19       /* BMP  */
#define SPR_AB0005                       20       /* BMP  */
#define SPR_AB0006                       21       /* BMP  */
#define SPR_AB0007                       22       /* BMP  */
#define SPR_AB0008                       23       /* BMP  */
#define SPR_AB0009                       24       /* BMP  */
#define SPR_AB0010                       25       /* BMP  */
#define SPR_AB0011                       26       /* BMP  */
#define SPR_AB0012                       27       /* BMP  */
#define SPR_AB0013                       28       /* BMP  */
#define SPR_AB0014                       29       /* BMP  */
#define SPR_AC0001                       30       /* BMP  */
#define SPR_AC0002                       31       /* BMP  */
#define SPR_AC0003                       32       /* BMP  */
#define SPR_AC0004                       33       /* BMP  */
#define SPR_AC0005                       34       /* BMP  */
#define SPR_AC0006                       35       /* BMP  */
#define SPR_AC0007                       36       /* BMP  */
#define SPR_AC0008                       37       /* BMP  */
#define SPR_AC0009                       38       /* BMP  */
#define SPR_AC0010                       39       /* BMP  */
#define SPR_AC0011                       40       /* BMP  */
#define SPR_AC0012                       41       /* BMP  */
#define SPR_AC0013                       42       /* BMP  */
#define SPR_AC0014                       43       /* BMP  */
#define SPR_ACKATOO                      44       /* JPEG */
#define SPR_AD0001                       45       /* BMP  */
#define SPR_AD0002                       46       /* BMP  */
#define SPR_AD0003                       47       /* BMP  */
#define SPR_AD0004                       48       /* BMP  */
#define SPR_AD0005                       49       /* BMP  */
#define SPR_AD0006                       50       /* BMP  */
#define SPR_AD0007                       51       /* BMP  */
#define SPR_AD0008                       52       /* BMP  */
#define SPR_AD0009                       53       /* BMP  */
#define SPR_AD0010                       54       /* BMP  */
#define SPR_AD0011                       55       /* BMP  */
#define SPR_AD0012                       56       /* BMP  */
#define SPR_AD0013                       57       /* BMP  */
#define SPR_AD0014                       58       /* BMP  */
#define SPR_AE0001                       59       /* BMP  */
#define SPR_AE0002                       60       /* BMP  */
#define SPR_AE0003                       61       /* BMP  */
#define SPR_AE0004                       62       /* BMP  */
#define SPR_AE0005                       63       /* BMP  */
#define SPR_AE0006                       64       /* BMP  */
#define SPR_AE0007                       65       /* BMP  */
#define SPR_AE0008                       66       /* BMP  */
#define SPR_AE0009                       67       /* BMP  */
#define SPR_AE0010                       68       /* BMP  */
#define SPR_AE0011                       69       /* BMP  */
#define SPR_AE0012                       70       /* BMP  */
#define SPR_AE0013                       71       /* BMP  */
#define SPR_AE0014                       72       /* BMP  */
#define SPR_AF0001                       73       /* BMP  */
#define SPR_AF0002                       74       /* BMP  */
#define SPR_AF0003                       75       /* BMP  */
#define SPR_AF0004                       76       /* BMP  */
#define SPR_AF0005                       77       /* BMP  */
#define SPR_AF0006                       78       /* BMP  */
#define SPR_AF0007                       79       /* BMP  */
#define SPR_AF0008                       80       /* BMP  */
#define SPR_AF0009                       81       /* BMP  */
#define SPR_AF0010                       82       /* BMP  */
#define SPR_AF0011                       83       /* BMP  */
#define SPR_AF0012                       84       /* BMP  */
#define SPR_AF0013                       85       /* BMP  */
#define SPR_AF0014                       86       /* BMP  */
#define SPR_AG0001                       87       /* BMP  */
#define SPR_AG0002                       88       /* BMP  */
#define SPR_AG0003                       89       /* BMP  */
#define SPR_AG0004                       90       /* BMP  */
#define SPR_AG0005                       91       /* BMP  */
#define SPR_AG0006                       92       /* BMP  */
#define SPR_AG0007                       93       /* BMP  */
#define SPR_AG0008                       94       /* BMP  */
#define SPR_AG0009                       95       /* BMP  */
#define SPR_AG0010                       96       /* BMP  */
#define SPR_AG0011                       97       /* BMP  */
#define SPR_AG0012                       98       /* BMP  */
#define SPR_AG0013                       99       /* BMP  */
#define SPR_AG0014                       100      /* BMP  */
#define SPR_AH0001                       101      /* BMP  */
#define SPR_AH0002                       102      /* BMP  */
#define SPR_AH0003                       103      /* BMP  */
#define SPR_AH0004                       104      /* BMP  */
#define SPR_AH0005                       105      /* BMP  */
#define SPR_AH0006                       106      /* BMP  */
#define SPR_AH0007                       107      /* BMP  */
#define SPR_AH0008                       108      /* BMP  */
#define SPR_AH0009                       109      /* BMP  */
#define SPR_AH0010                       110      /* BMP  */
#define SPR_AH0011                       111      /* BMP  */
#define SPR_AH0012                       112      /* BMP  */
#define SPR_AH0013                       113      /* BMP  */
#define SPR_AH0014                       114      /* BMP  */
#define SPR_AI0001                       115      /* BMP  */
#define SPR_AI0002                       116      /* BMP  */
#define SPR_AI0003                       117      /* BMP  */
#define SPR_AI0004                       118      /* BMP  */
#define SPR_AI0005                       119      /* BMP  */
#define SPR_AI0006                       120      /* BMP  */
#define SPR_AI0007                       121      /* BMP  */
#define SPR_AI0008                       122      /* BMP  */
#define SPR_AI0009                       123      /* BMP  */
#define SPR_AI0010                       124      /* BMP  */
#define SPR_AI0011                       125      /* BMP  */
#define SPR_AI0012                       126      /* BMP  */
#define SPR_AI0013                       127      /* BMP  */
#define SPR_AI0014                       128      /* BMP  */
#define SPR_AISORMBA                     129      /* BMP  */
#define SPR_AISORMBA_INV                 130      /* JPEG */
#define SPR_AJ0001                       131      /* BMP  */
#define SPR_AJ0002                       132      /* BMP  */
#define SPR_AJ0003                       133      /* BMP  */
#define SPR_AJ0004                       134      /* BMP  */
#define SPR_AJ0005                       135      /* BMP  */
#define SPR_AJ0006                       136      /* BMP  */
#define SPR_AJ0007                       137      /* BMP  */
#define SPR_AJ0008                       138      /* BMP  */
#define SPR_AJ0009                       139      /* BMP  */
#define SPR_AJ0010                       140      /* BMP  */
#define SPR_AJ0011                       141      /* BMP  */
#define SPR_AJ0012                       142      /* BMP  */
#define SPR_AJ0013                       143      /* BMP  */
#define SPR_AJ0014                       144      /* BMP  */
#define SPR_AKT_ATK1                     145      /* BMP  */
#define SPR_AKT_DEAD                     146      /* BMP  */
#define SPR_AKT_MOV1                     147      /* BMP  */
#define SPR_AKT_MOV2                     148      /* BMP  */
#define SPR_AKT_SPIT                     149      /* BMP  */
#define SPR_AKT_STILL                    150      /* BMP  */
#define SPR_ARENA                        151      /* BMP  */
#define SPR_ARENAF                       152      /* JPEG */
#define SPR_ARENAHQ                      153      /* BMP  */
#define SPR_ARENAHQF                     154      /* JPEG */
#define SPR_ASLEEP                       155      /* BMP  */
#define SPR_AWD00TMITG                   156      /* BMP  */
#define SPR_AWD01GOLD                    157      /* BMP  */
#define SPR_AWD02SILVER                  158      /* BMP  */
#define SPR_AWD03BRONZE                  159      /* BMP  */
#define SPR_AWD04PIT                     160      /* BMP  */
#define SPR_AWD05PIT                     161      /* BMP  */
#define SPR_AWD06PIT                     162      /* BMP  */
#define SPR_B_CANNON                     163      /* BMP  */
#define SPR_B_CANNON_F                   164      /* BMP  */
#define SPR_B_DUELGUN                    165      /* BMP  */
#define SPR_B_DUELGUN_F                  166      /* BMP  */
#define SPR_B_GUN                        167      /* BMP  */
#define SPR_B_GUN_F                      168      /* BMP  */
#define SPR_B_MACHGUN                    169      /* BMP  */
#define SPR_B_MACHGUN_F                  170      /* BMP  */
#define SPR_BAR_CAGE                     171      /* BMP  */
#define SPR_BAR_DRAG                     172      /* BMP  */
#define SPR_BAR_HULL                     173      /* BMP  */
#define SPR_BAR_STRESS                   174      /* BMP  */
#define SPR_BAR_VCAGE                    175      /* BMP  */
#define SPR_BASE                         176      /* BMP  */
#define SPR_BASEF                        177      /* JPEG */
#define SPR_BAT_BAM                      178      /* BMP  */
#define SPR_BAT_CRUNCH                   179      /* BMP  */
#define SPR_BERVUL                       180      /* JPEG */
#define SPR_BFC                          181      /* BMP  */
#define SPR_BFCF                         182      /* JPEG */
#define SPR_BFCGUY00                     183      /* JPEG */
#define SPR_BFCGUY01                     184      /* JPEG */
#define SPR_BFCGUY02                     185      /* JPEG */
#define SPR_BFCGUY03                     186      /* JPEG */
#define SPR_BFCGUY04                     187      /* JPEG */
#define SPR_BGEN1_1                      188      /* BMP  */
#define SPR_BGEN1_2                      189      /* BMP  */
#define SPR_BGEN1_INV                    190      /* JPEG */
#define SPR_BGEN2_1                      191      /* BMP  */
#define SPR_BGEN2_2                      192      /* BMP  */
#define SPR_BGEN2_3                      193      /* BMP  */
#define SPR_BGEN2_INV                    194      /* JPEG */
#define SPR_BGEN3_1                      195      /* BMP  */
#define SPR_BGEN3_2                      196      /* BMP  */
#define SPR_BGEN3_3                      197      /* BMP  */
#define SPR_BGEN3_4                      198      /* BMP  */
#define SPR_BGEN3_5                      199      /* BMP  */
#define SPR_BGEN3_6                      200      /* BMP  */
#define SPR_BGEN3_INV                    201      /* JPEG */
#define SPR_BIG_ATK1                     202      /* BMP  */
#define SPR_BIG_ATK2                     203      /* BMP  */
#define SPR_BIG_ATK3                     204      /* BMP  */
#define SPR_BIG_DEAD                     205      /* BMP  */
#define SPR_BIG_MOV1                     206      /* BMP  */
#define SPR_BIG_MOV2                     207      /* BMP  */
#define SPR_BIG_MOV3                     208      /* BMP  */
#define SPR_BIG_MOV4                     209      /* BMP  */
#define SPR_BIG_STILL                    210      /* BMP  */
#define SPR_BIGASAURUS                   211      /* JPEG */
#define SPR_BIOCITE                      212      /* BMP  */
#define SPR_BIOCITE_INV                  213      /* JPEG */
#define SPR_BORED                        214      /* BMP  */
#define SPR_BRV_DEAD                     215      /* BMP  */
#define SPR_BRV_EAT                      216      /* BMP  */
#define SPR_BRV_MOV1                     217      /* BMP  */
#define SPR_BRV_MOV2                     218      /* BMP  */
#define SPR_BRV_MOV3                     219      /* BMP  */
#define SPR_BRV_STILL1                   220      /* BMP  */
#define SPR_BRV_STILL2                   221      /* BMP  */
#define SPR_BRV_STILL3                   222      /* BMP  */
#define SPR_BTURRET                      223      /* BMP  */
#define SPR_BTURRET_CANNON               224      /* JPEG */
#define SPR_BTURRET_DUELGUN              225      /* JPEG */
#define SPR_BTURRET_GUN                  226      /* JPEG */
#define SPR_BTURRET_MACHGUN              227      /* JPEG */
#define SPR_BUILD                        228      /* BMP  */
#define SPR_CAGE0                        229      /* BMP  */
#define SPR_CAGE0_BROKEN                 230      /* BMP  */
#define SPR_CAGE0_INV                    231      /* JPEG */
#define SPR_CAGE1                        232      /* BMP  */
#define SPR_CAGE1_BROKEN                 233      /* BMP  */
#define SPR_CAGE1_INV                    234      /* JPEG */
#define SPR_CAGE2                        235      /* BMP  */
#define SPR_CAGE2_BROKEN                 236      /* BMP  */
#define SPR_CAGE2_INV                    237      /* JPEG */
#define SPR_CAGE3                        238      /* BMP  */
#define SPR_CAGE3_BROKEN                 239      /* BMP  */
#define SPR_CAGE3_INV                    240      /* JPEG */
#define SPR_CAGE4                        241      /* BMP  */
#define SPR_CAGE4_BROKEN                 242      /* BMP  */
#define SPR_CAGE4_INV                    243      /* JPEG */
#define SPR_CAGE5                        244      /* BMP  */
#define SPR_CAGE5_BROKEN                 245      /* BMP  */
#define SPR_CAGE5_INV                    246      /* JPEG */
#define SPR_CAGEPTR                      247      /* BMP  */
#define SPR_CAMPFIRE1                    248      /* BMP  */
#define SPR_CAMPFIRE2                    249      /* BMP  */
#define SPR_CAMPFIRE3                    250      /* BMP  */
#define SPR_CAMPFIREF                    251      /* JPEG */
#define SPR_CANNEDFURBIT                 252      /* BMP  */
#define SPR_CANNEDFURBIT_INV             253      /* JPEG */
#define SPR_CCH_ATK                      254      /* BMP  */
#define SPR_CCH_DEAD                     255      /* BMP  */
#define SPR_CCH_MOV1                     256      /* BMP  */
#define SPR_CCH_MOV2                     257      /* BMP  */
#define SPR_CCH_STILL1                   258      /* BMP  */
#define SPR_CCH_STILL2                   259      /* BMP  */
#define SPR_CCH_STILL                    260      /* BMP  */
#define SPR_CGEN_1                       261      /* BMP  */
#define SPR_CGEN_2                       262      /* BMP  */
#define SPR_CGEN_3                       263      /* BMP  */
#define SPR_CGEN_INV                     264      /* JPEG */
#define SPR_CHEECH                       265      /* JPEG */
#define SPR_CITYA                        266      /* BMP  */
#define SPR_CITYAF                       267      /* JPEG */
#define SPR_CITYB                        268      /* BMP  */
#define SPR_CITYBF                       269      /* JPEG */
#define SPR_CITYC                        270      /* BMP  */
#define SPR_CITYCF                       271      /* JPEG */
#define SPR_CLAW0                        272      /* BMP  */
#define SPR_CLAW0_CLOSED                 273      /* BMP  */
#define SPR_CLAW0_INV                    274      /* JPEG */
#define SPR_CLAW1                        275      /* BMP  */
#define SPR_CLAW1_CLOSED                 276      /* BMP  */
#define SPR_CLAW1_INV                    277      /* JPEG */
#define SPR_CLAW2                        278      /* BMP  */
#define SPR_CLAW2_CLOSED                 279      /* BMP  */
#define SPR_CLAW2_INV                    280      /* JPEG */
#define SPR_CLAW3                        281      /* BMP  */
#define SPR_CLAW3_CLOSED                 282      /* BMP  */
#define SPR_CLAW3_INV                    283      /* JPEG */
#define SPR_CLAW4                        284      /* BMP  */
#define SPR_CLAW4_CLOSED                 285      /* BMP  */
#define SPR_CLAW4_INV                    286      /* JPEG */
#define SPR_CLAWL1_INV                   287      /* JPEG */
#define SPR_CLAWL2_INV                   288      /* JPEG */
#define SPR_CLAWL3_INV                   289      /* JPEG */
#define SPR_CLAWL4_INV                   290      /* JPEG */
#define SPR_CONFUSED                     291      /* BMP  */
#define SPR_CORNSTALK                    292      /* BMP  */
#define SPR_CORNSTALK_PIC                293      /* JPEG */
#define SPR_CRASHSITE                    294      /* BMP  */
#define SPR_CRASHSITEF                   295      /* JPEG */
#define SPR_CROSSHAIRS                   296      /* BMP  */
#define SPR_CROSSHAIRS_BUILD             297      /* BMP  */
#define SPR_CROSSHAIRS_INTERFACE         298      /* BMP  */
#define SPR_CRY_ATK1                     299      /* BMP  */
#define SPR_CRY_ATK2                     300      /* BMP  */
#define SPR_CRY_ATK3                     301      /* BMP  */
#define SPR_CRY_ATK4                     302      /* BMP  */
#define SPR_CRY_DEAD                     303      /* BMP  */
#define SPR_CRY_MOV1                     304      /* BMP  */
#define SPR_CRY_MOV2                     305      /* BMP  */
#define SPR_CRY_MOV3                     306      /* BMP  */
#define SPR_CRY_SHIP                     307      /* BMP  */
#define SPR_CRY_SHIPF                    308      /* JPEG */
#define SPR_CRY_STILL                    309      /* BMP  */
#define SPR_CRYSILLIAN                   310      /* JPEG */
#define SPR_CRYSILLIANRUINS              311      /* BMP  */
#define SPR_CRYSILLIANRUINSF             312      /* JPEG */
#define SPR_DART1                        313      /* BMP  */
#define SPR_DART1_INV                    314      /* JPEG */
#define SPR_DART2                        315      /* BMP  */
#define SPR_DART2_INV                    316      /* JPEG */
#define SPR_DART3                        317      /* BMP  */
#define SPR_DART3_INV                    318      /* JPEG */
#define SPR_DART4                        319      /* BMP  */
#define SPR_DART4_INV                    320      /* JPEG */
#define SPR_DART5                        321      /* BMP  */
#define SPR_DART5_INV                    322      /* JPEG */
#define SPR_DART6                        323      /* BMP  */
#define SPR_DART6_INV                    324      /* JPEG */
#define SPR_DART7                        325      /* BMP  */
#define SPR_DART7_INV                    326      /* JPEG */
#define SPR_DEAD                         327      /* BMP  */
#define SPR_DEBRIES1                     328      /* BMP  */
#define SPR_DETOX                        329      /* BMP  */
#define SPR_DETOX_INV                    330      /* JPEG */
#define SPR_DRA_ATK1                     331      /* BMP  */
#define SPR_DRA_ATK2                     332      /* BMP  */
#define SPR_DRA_ATK3                     333      /* BMP  */
#define SPR_DRA_ATK4                     334      /* BMP  */
#define SPR_DRA_DEAD                     335      /* BMP  */
#define SPR_DRA_MOV1                     336      /* BMP  */
#define SPR_DRA_MOV2                     337      /* BMP  */
#define SPR_DRA_MOV3                     338      /* BMP  */
#define SPR_DRA_MOV4                     339      /* BMP  */
#define SPR_DRAG_CAGE                    340      /* BMP  */
#define SPR_DRAG_MONST                   341      /* BMP  */
#define SPR_DRAGOONIGON                  342      /* JPEG */
#define SPR_DREXLER                      343      /* JPEG */
#define SPR_DRX_ATK1                     344      /* BMP  */
#define SPR_DRX_ATK2                     345      /* BMP  */
#define SPR_DRX_DEAD                     346      /* BMP  */
#define SPR_DRX_EAT1                     347      /* BMP  */
#define SPR_DRX_EAT2                     348      /* BMP  */
#define SPR_DRX_MOV1                     349      /* BMP  */
#define SPR_DRX_MOV2                     350      /* BMP  */
#define SPR_DRX_MOV3                     351      /* BMP  */
#define SPR_DRX_STILL                    352      /* BMP  */
#define SPR_EATING                       353      /* BMP  */
#define SPR_ENCL1                        354      /* BMP  */
#define SPR_ENCL1_DEAD                   355      /* BMP  */
#define SPR_ENCL1_FLOOR                  356      /* JPEG */
#define SPR_ENCL1_INV                    357      /* JPEG */
#define SPR_ENCL2                        358      /* BMP  */
#define SPR_ENCL2_DEAD                   359      /* BMP  */
#define SPR_ENCL2_FLOOR                  360      /* JPEG */
#define SPR_ENCL2_INV                    361      /* JPEG */
#define SPR_ENCL3                        362      /* BMP  */
#define SPR_ENCL3_DEAD                   363      /* BMP  */
#define SPR_ENCL3_FLOOR                  364      /* JPEG */
#define SPR_ENCL3_INV                    365      /* JPEG */
#define SPR_ENCL_BORD_ANEX               366      /* BMP  */
#define SPR_ENCL_BORD_BAD                367      /* BMP  */
#define SPR_ENCL_BORD                    368      /* BMP  */
#define SPR_ENCL_CENT_ANEX               369      /* BMP  */
#define SPR_ENCL_CENT_BAD                370      /* BMP  */
#define SPR_ENCL_CENT                    371      /* BMP  */
#define SPR_ENF_CANNON                   372      /* BMP  */
#define SPR_ENF_CANNON_F2                373      /* BMP  */
#define SPR_ENF_CANNON_F                 374      /* BMP  */
#define SPR_ENF_MOV1                     375      /* BMP  */
#define SPR_ENF_MOV2                     376      /* BMP  */
#define SPR_ENF_MOV3                     377      /* BMP  */
#define SPR_ENF_MOV4                     378      /* BMP  */
#define SPR_ENF_STILL                    379      /* BMP  */
#define SPR_ENFORCERF                    380      /* JPEG */
#define SPR_EXCLAM                       381      /* BMP  */
#define SPR_EYESTALKSHOOTS               382      /* BMP  */
#define SPR_EYESTALKSHOOTS_INV           383      /* JPEG */
#define SPR_FERN                         384      /* BMP  */
#define SPR_FERN_DEAD                    385      /* BMP  */
#define SPR_FERN_PIC                     386      /* JPEG */
#define SPR_FIRBIT_DEAD                  387      /* BMP  */
#define SPR_FIRBIT_EAT1                  388      /* BMP  */
#define SPR_FIRBIT_EAT2                  389      /* BMP  */
#define SPR_FIRBIT_EAT                   390      /* BMP  */
#define SPR_FIRBIT                       391      /* JPEG */
#define SPR_FIRBIT_MOV1                  392      /* BMP  */
#define SPR_FIRBIT_MOV2                  393      /* BMP  */
#define SPR_FIRBIT_STILL2                394      /* BMP  */
#define SPR_FIRBIT_STILL                 395      /* BMP  */
#define SPR_FIREBALL                     396      /* BMP  */
#define SPR_FISEC                        397      /* BMP  */
#define SPR_FISECF                       398      /* JPEG */
#define SPR_FISECGUY00                   399      /* JPEG */
#define SPR_FISECGUY01                   400      /* JPEG */
#define SPR_FISECGUY02                   401      /* JPEG */
#define SPR_FISECGUY03                   402      /* JPEG */
#define SPR_FISECGUY04                   403      /* JPEG */
#define SPR_FRG_ATK1                     404      /* BMP  */
#define SPR_FRG_ATK2                     405      /* BMP  */
#define SPR_FRG_DEAD                     406      /* BMP  */
#define SPR_FRG_MOV1                     407      /* BMP  */
#define SPR_FRG_MOV2                     408      /* BMP  */
#define SPR_FRG_MOV3                     409      /* BMP  */
#define SPR_FRG_STILL1                   410      /* BMP  */
#define SPR_FRG_STILL2                   411      /* BMP  */
#define SPR_FRG_STILL3                   412      /* BMP  */
#define SPR_FRG_STILL                    413      /* BMP  */
#define SPR_FRIEDCHICKEN_INV             414      /* JPEG */
#define SPR_FROGERT                      415      /* JPEG */
#define SPR_GAMEOVER                     416      /* BMP  */
#define SPR_GEARBASE                     417      /* BMP  */
#define SPR_GEARCASE                     418      /* BMP  */
#define SPR_GEARTOOTH                    419      /* BMP  */
#define SPR_GLOWINGLIQUID                420      /* BMP  */
#define SPR_GLOWINGLIQUID_INV            421      /* JPEG */
#define SPR_GOL_DEAD1                    422      /* BMP  */
#define SPR_GOL_DEAD2                    423      /* BMP  */
#define SPR_GOL_EAT1                     424      /* BMP  */
#define SPR_GOL_EAT2                     425      /* BMP  */
#define SPR_GOL_EAT3                     426      /* BMP  */
#define SPR_GOL_MOV1                     427      /* BMP  */
#define SPR_GOL_MOV2                     428      /* BMP  */
#define SPR_GOL_MOV3                     429      /* BMP  */
#define SPR_GOL_MOV4                     430      /* BMP  */
#define SPR_GOL_MOV5                     431      /* BMP  */
#define SPR_GOL_MOV6                     432      /* BMP  */
#define SPR_GOL_STILL                    433      /* BMP  */
#define SPR_GOLGITHAN                    434      /* JPEG */
#define SPR_GREENCRYSTALS                435      /* BMP  */
#define SPR_GREENCRYSTALS_INV            436      /* JPEG */
#define SPR_GRNNOPOW                     437      /* BMP  */
#define SPR_GRNOFF                       438      /* BMP  */
#define SPR_GRNON                        439      /* BMP  */
#define SPR_GUN_1RACHET                  440      /* BMP  */
#define SPR_GUN_1RACHET_F                441      /* BMP  */
#define SPR_GUN_1RACHET_INV              442      /* JPEG */
#define SPR_GUN_2LANCER                  443      /* BMP  */
#define SPR_GUN_2LANCER_F                444      /* BMP  */
#define SPR_GUN_2LANCER_INV              445      /* JPEG */
#define SPR_GUN_2RUMBLER                 446      /* BMP  */
#define SPR_GUN_2RUMBLER_F               447      /* BMP  */
#define SPR_GUN_2RUMBLER_INV             448      /* JPEG */
#define SPR_GUN_3INCINERATOR             449      /* BMP  */
#define SPR_GUN_3INCINERATOR_INV         450      /* JPEG */
#define SPR_GUN_3MORNINGSTAR             451      /* BMP  */
#define SPR_GUN_3MORNINGSTAR_F           452      /* BMP  */
#define SPR_GUN_3MORNINGSTAR_INV         453      /* JPEG */
#define SPR_GUN_3RAILGUN                 454      /* BMP  */
#define SPR_GUN_3RAILGUN_F               455      /* BMP  */
#define SPR_GUN_3RAILGUN_INV             456      /* JPEG */
#define SPR_GUN_4PULSAR                  457      /* BMP  */
#define SPR_GUN_4PULSAR_F                458      /* BMP  */
#define SPR_GUN_4PULSAR_INV              459      /* JPEG */
#define SPR_GUN_4PYROCLASTER             460      /* BMP  */
#define SPR_GUN_4PYROCLASTER_F           461      /* BMP  */
#define SPR_GUN_4PYROCLASTER_INV         462      /* JPEG */
#define SPR_GUN_4STORMHAND               463      /* BMP  */
#define SPR_GUN_4STORMHAND_F             464      /* BMP  */
#define SPR_GUN_4STORMHAND_INV           465      /* JPEG */
#define SPR_GUN_4SUNSTRIKER              466      /* BMP  */
#define SPR_GUN_4SUNSTRIKER_F            467      /* BMP  */
#define SPR_GUN_4SUNSTRIKER_INV          468      /* JPEG */
#define SPR_GUN_5DEATHRAY                469      /* BMP  */
#define SPR_GUN_5DEATHRAY_F              470      /* BMP  */
#define SPR_GUN_5DEATHRAY_INV            471      /* JPEG */
#define SPR_HALO                         472      /* BMP  */
#define SPR_HAPPY                        473      /* BMP  */
#define SPR_HARVESTER                    474      /* JPEG */
#define SPR_HELP0                        475      /* JPEG */
#define SPR_HINT1_INV                    476      /* JPEG */
#define SPR_HINT2_INV                    477      /* JPEG */
#define SPR_HIP_DEAD                     478      /* BMP  */
#define SPR_HIP_MOV1                     479      /* BMP  */
#define SPR_HIP_MOV2                     480      /* BMP  */
#define SPR_HIP_STILL1                   481      /* BMP  */
#define SPR_HIP_STILL2                   482      /* BMP  */
#define SPR_HIPPI                        483      /* JPEG */
#define SPR_HNT_ATK                      484      /* BMP  */
#define SPR_HNT_DEAD                     485      /* BMP  */
#define SPR_HNT_MOV1                     486      /* BMP  */
#define SPR_HNT_MOV2                     487      /* BMP  */
#define SPR_HNT_STILL                    488      /* BMP  */
#define SPR_HOLE                         489      /* BMP  */
#define SPR_HOLEEYES                     490      /* BMP  */
#define SPR_HOLEF                        491      /* JPEG */
#define SPR_HOV_ATK                      492      /* BMP  */
#define SPR_HOV_DEAD                     493      /* BMP  */
#define SPR_HOV_MOV1                     494      /* BMP  */
#define SPR_HOV_MOV2                     495      /* BMP  */
#define SPR_HOV_STILL                    496      /* BMP  */
#define SPR_HOVELER                      497      /* JPEG */
#define SPR_HRV                          498      /* BMP  */
#define SPR_HRV_GUN                      499      /* BMP  */
#define SPR_HTREE                        500      /* BMP  */
#define SPR_HTREE_DEAD2                  501      /* BMP  */
#define SPR_HTREE_DEAD                   502      /* BMP  */
#define SPR_HTREE_PIC                    503      /* JPEG */
#define SPR_HTREE_STILL1                 504      /* BMP  */
#define SPR_HTREE_STILL2                 505      /* BMP  */
#define SPR_HTREE_STILL3                 506      /* BMP  */
#define SPR_HUD                          507      /* BMP  */
#define SPR_HULL0                        508      /* BMP  */
#define SPR_HULL0_INV                    509      /* JPEG */
#define SPR_HULL1                        510      /* BMP  */
#define SPR_HULL1_INV                    511      /* JPEG */
#define SPR_HULL2                        512      /* BMP  */
#define SPR_HULL2_INV                    513      /* JPEG */
#define SPR_HULL3                        514      /* BMP  */
#define SPR_HULL3_INV                    515      /* JPEG */
#define SPR_HULL4                        516      /* BMP  */
#define SPR_HULL4_INV                    517      /* JPEG */
#define SPR_HULL5                        518      /* BMP  */
#define SPR_HULL5_INV                    519      /* JPEG */
#define SPR_HUNGRY                       520      /* BMP  */
#define SPR_HUNTER                       521      /* JPEG */
#define SPR_HUNTERSHIP                   522      /* BMP  */
#define SPR_HX12                         523      /* BMP  */
#define SPR_HX12_INV                     524      /* JPEG */
#define SPR_IHB77                        525      /* BMP  */
#define SPR_IHB77_INV                    526      /* JPEG */
#define SPR_INFECTED                     527      /* BMP  */
#define SPR_JMART                        528      /* BMP  */
#define SPR_JMARTF                       529      /* JPEG */
#define SPR_JMARTGUY00                   530      /* JPEG */
#define SPR_JMARTGUY01                   531      /* JPEG */
#define SPR_JMARTGUY02                   532      /* JPEG */
#define SPR_JMARTGUY03                   533      /* JPEG */
#define SPR_JMARTGUY04                   534      /* JPEG */
#define SPR_JP_CORNSTALK_PIC             535      /* BMP  */
#define SPR_JP_SHRUB_PIC                 536      /* BMP  */
#define SPR_JP_STALK_PIC                 537      /* BMP  */
#define SPR_JP_TOURISTS_PIC              538      /* BMP  */
#define SPR_JR19AZF                      539      /* BMP  */
#define SPR_JR19AZF_INV                  540      /* JPEG */
#define SPR_JUMPGATE                     541      /* BMP  */
#define SPR_KEY_ALT                      542      /* BMP  */
#define SPR_KEY_CTRL                     543      /* BMP  */
#define SPR_KEY_SHIFT                    544      /* BMP  */
#define SPR_KEY_TAB                      545      /* BMP  */
#define SPR_KEY_WIN                      546      /* BMP  */
#define SPR_KMENU                        547      /* BMP  */
#define SPR_KRAKIN                       548      /* JPEG */
#define SPR_KRK_ATK1                     549      /* BMP  */
#define SPR_KRK_ATK2                     550      /* BMP  */
#define SPR_KRK_ATK3                     551      /* BMP  */
#define SPR_KRK_DEAD1                    552      /* BMP  */
#define SPR_KRK_DEAD2                    553      /* BMP  */
#define SPR_KRK_MOV1                     554      /* BMP  */
#define SPR_KRK_MOV2                     555      /* BMP  */
#define SPR_KRK_MOV3                     556      /* BMP  */
#define SPR_KRK_MOV4                     557      /* BMP  */
#define SPR_KRK_MOV5                     558      /* BMP  */
#define SPR_KRK_MOV6                     559      /* BMP  */
#define SPR_KRK_STILL                    560      /* BMP  */
#define SPR_KRL_DEAD                     561      /* BMP  */
#define SPR_KRL_MOV1                     562      /* BMP  */
#define SPR_KRL_MOV2                     563      /* BMP  */
#define SPR_KRL_STILL                    564      /* BMP  */
#define SPR_KRULASITE                    565      /* JPEG */
#define SPR_LYKEDOFAN                    566      /* BMP  */
#define SPR_LYKEDOFAN_INV                567      /* JPEG */
#define SPR_MAL_ATK1                     568      /* BMP  */
#define SPR_MAL_ATK2                     569      /* BMP  */
#define SPR_MAL_ATK3                     570      /* BMP  */
#define SPR_MAL_DEAD                     571      /* BMP  */
#define SPR_MAL_EAT1                     572      /* BMP  */
#define SPR_MAL_EAT2                     573      /* BMP  */
#define SPR_MAL_MOV1                     574      /* BMP  */
#define SPR_MAL_MOV2                     575      /* BMP  */
#define SPR_MAL_MOV3                     576      /* BMP  */
#define SPR_MAL_MOV4                     577      /* BMP  */
#define SPR_MAL_MOV5                     578      /* BMP  */
#define SPR_MAL_STILL1                   579      /* BMP  */
#define SPR_MAL_STILL2                   580      /* BMP  */
#define SPR_MAL_STILL3                   581      /* BMP  */
#define SPR_MAL_STILL4                   582      /* BMP  */
#define SPR_MALACUMEBIT                  583      /* JPEG */
#define SPR_MAMOTHQUITO                  584      /* JPEG */
#define SPR_MARJACOLA                    585      /* BMP  */
#define SPR_MARJACOLA_INV                586      /* JPEG */
#define SPR_MBK_ATK                      587      /* BMP  */
#define SPR_MBK_DEAD                     588      /* BMP  */
#define SPR_MBK_MOV1                     589      /* BMP  */
#define SPR_MBK_MOV2                     590      /* BMP  */
#define SPR_MBK_STILL                    591      /* BMP  */
#define SPR_MEEKER                       592      /* JPEG */
#define SPR_MEK_ATK1                     593      /* BMP  */
#define SPR_MEK_ATK2                     594      /* BMP  */
#define SPR_MEK_DEAD                     595      /* BMP  */
#define SPR_MEK_MOV1                     596      /* BMP  */
#define SPR_MEK_MOV2                     597      /* BMP  */
#define SPR_MEK_STILL1                   598      /* BMP  */
#define SPR_MEK_STILL2                   599      /* BMP  */
#define SPR_MEK_STILL3                   600      /* BMP  */
#define SPR_MENF_MOV1                    601      /* BMP  */
#define SPR_MENF_MOV2                    602      /* BMP  */
#define SPR_MENF_MOV3                    603      /* BMP  */
#define SPR_MENF_MOV4                    604      /* BMP  */
#define SPR_MENF_STILL                   605      /* BMP  */
#define SPR_MENFORCERF                   606      /* JPEG */
#define SPR_MERCHANT00                   607      /* JPEG */
#define SPR_MERCHANT01                   608      /* JPEG */
#define SPR_MERCHANT02                   609      /* JPEG */
#define SPR_MERCHANT03                   610      /* JPEG */
#define SPR_MERCHANT04                   611      /* JPEG */
#define SPR_METAL1                       612      /* BMP  */
#define SPR_METAL2                       613      /* BMP  */
#define SPR_METAL3                       614      /* BMP  */
#define SPR_MIM_ATK1                     615      /* BMP  */
#define SPR_MIM_ATK2                     616      /* BMP  */
#define SPR_MIM_MOV1                     617      /* BMP  */
#define SPR_MIM_MOV2                     618      /* BMP  */
#define SPR_MIM_MOV3                     619      /* BMP  */
#define SPR_MIM_STILL                    620      /* BMP  */
#define SPR_MIMMACK                      621      /* JPEG */
#define SPR_MIS_00                       622      /* BMP  */
#define SPR_MIS_01                       623      /* BMP  */
#define SPR_MIS_02                       624      /* BMP  */
#define SPR_MIS_03                       625      /* BMP  */
#define SPR_MIS_04                       626      /* BMP  */
#define SPR_MIS_05                       627      /* BMP  */
#define SPR_MIS_06                       628      /* BMP  */
#define SPR_MIS_10                       629      /* BMP  */
#define SPR_MIS_1                        630      /* BMP  */
#define SPR_MIS_2                        631      /* BMP  */
#define SPR_MIS_3                        632      /* BMP  */
#define SPR_MIS_4                        633      /* BMP  */
#define SPR_MIS_5                        634      /* BMP  */
#define SPR_MIS_6                        635      /* BMP  */
#define SPR_MIS_7                        636      /* BMP  */
#define SPR_MIS_8                        637      /* BMP  */
#define SPR_MIS_9                        638      /* BMP  */
#define SPR_MIXEDVEGITABLES              639      /* BMP  */
#define SPR_MIXEDVEGITABLES_INV          640      /* JPEG */
#define SPR_MMQ_ATK1                     641      /* BMP  */
#define SPR_MMQ_MOV1                     642      /* BMP  */
#define SPR_MMQ_MOV2                     643      /* BMP  */
#define SPR_MMQ_MOV3                     644      /* BMP  */
#define SPR_MOL_ATK1                     645      /* BMP  */
#define SPR_MOL_ATK2                     646      /* BMP  */
#define SPR_MOL_DEAD                     647      /* BMP  */
#define SPR_MOL_EAT1                     648      /* BMP  */
#define SPR_MOL_EAT2                     649      /* BMP  */
#define SPR_MOL_MOV1                     650      /* BMP  */
#define SPR_MOL_MOV2                     651      /* BMP  */
#define SPR_MOL_MOV3                     652      /* BMP  */
#define SPR_MOL_MOV4                     653      /* BMP  */
#define SPR_MOL_STILL                    654      /* BMP  */
#define SPR_MOLBER                       655      /* JPEG */
#define SPR_MONEY1                       656      /* BMP  */
#define SPR_MONEY2                       657      /* BMP  */
#define SPR_MONEY3                       658      /* BMP  */
#define SPR_MONEY4                       659      /* BMP  */
#define SPR_MONEY5                       660      /* BMP  */
#define SPR_MONEY6                       661      /* BMP  */
#define SPR_MONEY_INV                    662      /* JPEG */
#define SPR_MORODULB                     663      /* BMP  */
#define SPR_MORODULB_INV                 664      /* JPEG */
#define SPR_MUBARK                       665      /* JPEG */
#define SPR_MUTATE                       666      /* BMP  */
#define SPR_NANOBOTS                     667      /* BMP  */
#define SPR_NANOBOTS_INV                 668      /* JPEG */
#define SPR_NO_BIG_PIC                   669      /* JPEG */
#define SPR_NO_LIL_PIC                   670      /* BMP  */
#define SPR_NOPOWER                      671      /* BMP  */
#define SPR_ORC_ATK1_AXE                 672      /* BMP  */
#define SPR_ORC_ATK1_SPEAR               673      /* BMP  */
#define SPR_ORC_ATK2_AXE                 674      /* BMP  */
#define SPR_ORC_ATK2_SPEAR               675      /* BMP  */
#define SPR_ORC_ATK3_AXE                 676      /* BMP  */
#define SPR_ORC_ATK3_SPEAR               677      /* BMP  */
#define SPR_ORC_ATK_GUN                  678      /* BMP  */
#define SPR_ORC_DEAD                     679      /* BMP  */
#define SPR_ORC_MOV1_AXE                 680      /* BMP  */
#define SPR_ORC_MOV1_GUN                 681      /* BMP  */
#define SPR_ORC_MOV1_SPEAR               682      /* BMP  */
#define SPR_ORC_MOV2_AXE                 683      /* BMP  */
#define SPR_ORC_MOV2_GUN                 684      /* BMP  */
#define SPR_ORC_MOV2_SPEAR               685      /* BMP  */
#define SPR_ORC_STILL_AXE                686      /* BMP  */
#define SPR_ORC_STILL_GUN                687      /* BMP  */
#define SPR_ORC_STILL_SPEAR              688      /* BMP  */
#define SPR_ORICK00                      689      /* JPEG */
#define SPR_ORICK01                      690      /* JPEG */
#define SPR_ORICK02                      691      /* JPEG */
#define SPR_ORICK03                      692      /* JPEG */
#define SPR_ORICK04                      693      /* JPEG */
#define SPR_ORICK_BANCLAW                694      /* JPEG */
#define SPR_ORICK_DRACOMAJIA             695      /* JPEG */
#define SPR_ORICK_GRELBLADE              696      /* JPEG */
#define SPR_ORICK_MONROJO                697      /* JPEG */
#define SPR_ORICK_SKULIBULA              698      /* JPEG */
#define SPR_ORICKCAMP                    699      /* BMP  */
#define SPR_ORICKCAMPF                   700      /* JPEG */
#define SPR_P_CANNON                     701      /* BMP  */
#define SPR_P_CANNON_F                   702      /* BMP  */
#define SPR_P_GUN                        703      /* BMP  */
#define SPR_P_GUNF                       704      /* BMP  */
#define SPR_PISSED                       705      /* BMP  */
#define SPR_PITGUY00                     706      /* JPEG */
#define SPR_PITGUY01                     707      /* JPEG */
#define SPR_PITGUY02                     708      /* JPEG */
#define SPR_PITGUY03                     709      /* JPEG */
#define SPR_PITGUY04                     710      /* JPEG */
#define SPR_PITSHIP                      711      /* BMP  */
#define SPR_PITSHIPF                     712      /* JPEG */
#define SPR_POINTER                      713      /* BMP  */
#define SPR_POISENS                      714      /* BMP  */
#define SPR_POISENSF                     715      /* JPEG */
#define SPR_POLICE00                     716      /* JPEG */
#define SPR_POLICE01                     717      /* JPEG */
#define SPR_POLICE02                     718      /* JPEG */
#define SPR_POLICE03                     719      /* JPEG */
#define SPR_POLICE04                     720      /* JPEG */
#define SPR_POLICESTATION                721      /* BMP  */
#define SPR_POLICESTATIONF               722      /* JPEG */
#define SPR_POWEROFF                     723      /* BMP  */
#define SPR_PROJECT17                    724      /* BMP  */
#define SPR_PROJECT17_INV                725      /* JPEG */
#define SPR_PRREP00                      726      /* JPEG */
#define SPR_PRREP01                      727      /* JPEG */
#define SPR_PRREP02                      728      /* JPEG */
#define SPR_PRREP03                      729      /* JPEG */
#define SPR_PRREP04                      730      /* JPEG */
#define SPR_PRREP05                      731      /* JPEG */
#define SPR_PSY_1                        732      /* BMP  */
#define SPR_PSY_2                        733      /* BMP  */
#define SPR_PSYCOS                       734      /* BMP  */
#define SPR_PSYCOSF                      735      /* JPEG */
#define SPR_PURPLEROCK                   736      /* BMP  */
#define SPR_PURPLEROCK_INV               737      /* JPEG */
#define SPR_PYG_ATK1                     738      /* BMP  */
#define SPR_PYG_ATK2                     739      /* BMP  */
#define SPR_PYG_DEAD                     740      /* BMP  */
#define SPR_PYG_EAT                      741      /* BMP  */
#define SPR_PYG_MOV1                     742      /* BMP  */
#define SPR_PYG_MOV2                     743      /* BMP  */
#define SPR_PYG_STILL                    744      /* BMP  */
#define SPR_PYGMENT                      745      /* JPEG */
#define SPR_PYROS                        746      /* BMP  */
#define SPR_PYROSF                       747      /* JPEG */
#define SPR_QTF_MOV1                     748      /* BMP  */
#define SPR_QTF_MOV2                     749      /* BMP  */
#define SPR_QTF_MOV3                     750      /* BMP  */
#define SPR_QUITOFLY                     751      /* JPEG */
#define SPR_QUIVER                       752      /* JPEG */
#define SPR_QUV_ATK1                     753      /* BMP  */
#define SPR_QUV_ATK2                     754      /* BMP  */
#define SPR_QUV_STILL1                   755      /* BMP  */
#define SPR_QUV_STILL2                   756      /* BMP  */
#define SPR_R_CANNON                     757      /* BMP  */
#define SPR_R_CANNON_F                   758      /* BMP  */
#define SPR_R_DUELGUN                    759      /* BMP  */
#define SPR_R_DUELGUN_F                  760      /* BMP  */
#define SPR_R_GUN                        761      /* BMP  */
#define SPR_R_GUNF                       762      /* BMP  */
#define SPR_R_MACHGUN                    763      /* BMP  */
#define SPR_R_MACHGUN_F                  764      /* BMP  */
#define SPR_RAD_ATK                      765      /* BMP  */
#define SPR_RAD_DEAD                     766      /* BMP  */
#define SPR_RAD_MOV1                     767      /* BMP  */
#define SPR_RAD_MOV2                     768      /* BMP  */
#define SPR_RAD_STILL                    769      /* BMP  */
#define SPR_RADRUNNER                    770      /* JPEG */
#define SPR_RAIDER1                      771      /* BMP  */
#define SPR_RAIDER2                      772      /* BMP  */
#define SPR_RAIDER3                      773      /* BMP  */
#define SPR_RAIDER4                      774      /* BMP  */
#define SPR_RAIDER5                      775      /* BMP  */
#define SPR_RAIDER6                      776      /* BMP  */
#define SPR_RAIDER7                      777      /* BMP  */
#define SPR_RAIDER8                      778      /* BMP  */
#define SPR_RAIDER                       779      /* JPEG */
#define SPR_RAIDERCAMP                   780      /* BMP  */
#define SPR_RAIDERCAMPF                  781      /* JPEG */
#define SPR_RAIDERSHIP                   782      /* BMP  */
#define SPR_RAIDSHIPF                    783      /* JPEG */
#define SPR_RAR_ATK                      784      /* BMP  */
#define SPR_RAR_DEAD                     785      /* BMP  */
#define SPR_RAR_MOV1                     786      /* BMP  */
#define SPR_RAR_MOV2                     787      /* BMP  */
#define SPR_RAR_STILL                    788      /* BMP  */
#define SPR_RCH_ATK                      789      /* BMP  */
#define SPR_RCH_DEAD                     790      /* BMP  */
#define SPR_RCH_MOV1                     791      /* BMP  */
#define SPR_RCH_MOV2                     792      /* BMP  */
#define SPR_RCH_STILL                    793      /* BMP  */
#define SPR_RECEP                        794      /* JPEG */
#define SPR_REDROCK                      795      /* BMP  */
#define SPR_REDROCK_INV                  796      /* JPEG */
#define SPR_REF_BIOCITE                  797      /* BMP  */
#define SPR_REXREX                       798      /* JPEG */
#define SPR_RGEN1_1                      799      /* BMP  */
#define SPR_RGEN1_2                      800      /* BMP  */
#define SPR_RGEN1_INV                    801      /* JPEG */
#define SPR_RGEN2_1                      802      /* BMP  */
#define SPR_RGEN2_2                      803      /* BMP  */
#define SPR_RGEN2_3                      804      /* BMP  */
#define SPR_RGEN2_INV                    805      /* JPEG */
#define SPR_RGEN3_1                      806      /* BMP  */
#define SPR_RGEN3_2                      807      /* BMP  */
#define SPR_RGEN3_3                      808      /* BMP  */
#define SPR_RGEN3_4                      809      /* BMP  */
#define SPR_RGEN3_5                      810      /* BMP  */
#define SPR_RGEN3_6                      811      /* BMP  */
#define SPR_RGEN3_INV                    812      /* JPEG */
#define SPR_ROACHY                       813      /* JPEG */
#define SPR_ROPE1_INV                    814      /* JPEG */
#define SPR_ROPE2_INV                    815      /* JPEG */
#define SPR_ROPE3_INV                    816      /* JPEG */
#define SPR_ROPE4_INV                    817      /* JPEG */
#define SPR_ROZOLIN                      818      /* BMP  */
#define SPR_ROZOLIN_INV                  819      /* JPEG */
#define SPR_RRX_ATK1                     820      /* BMP  */
#define SPR_RRX_ATK2                     821      /* BMP  */
#define SPR_RRX_DEAD                     822      /* BMP  */
#define SPR_RRX_MOV1                     823      /* BMP  */
#define SPR_RRX_MOV2                     824      /* BMP  */
#define SPR_RRX_STILL                    825      /* BMP  */
#define SPR_RTURRET                      826      /* BMP  */
#define SPR_RTURRET_CANNON               827      /* JPEG */
#define SPR_RTURRET_DUELGUN              828      /* JPEG */
#define SPR_RTURRET_GUN                  829      /* JPEG */
#define SPR_RTURRET_MACHGUN              830      /* JPEG */
#define SPR_SCAN0_00                     831      /* BMP  */
#define SPR_SCAN0_01                     832      /* BMP  */
#define SPR_SCAN0_INV                    833      /* JPEG */
#define SPR_SCAN1_00                     834      /* BMP  */
#define SPR_SCAN1_01                     835      /* BMP  */
#define SPR_SCAN1_02                     836      /* BMP  */
#define SPR_SCAN1_03                     837      /* BMP  */
#define SPR_SCAN1_04                     838      /* BMP  */
#define SPR_SCAN1_05                     839      /* BMP  */
#define SPR_SCAN1_06                     840      /* BMP  */
#define SPR_SCAN1_07                     841      /* BMP  */
#define SPR_SCAN1_08                     842      /* BMP  */
#define SPR_SCAN1_09                     843      /* BMP  */
#define SPR_SCAN1_10                     844      /* BMP  */
#define SPR_SCAN1_11                     845      /* BMP  */
#define SPR_SCAN1_INV                    846      /* JPEG */
#define SPR_SCAN2_00                     847      /* BMP  */
#define SPR_SCAN2_01                     848      /* BMP  */
#define SPR_SCAN2_02                     849      /* BMP  */
#define SPR_SCAN2_03                     850      /* BMP  */
#define SPR_SCAN2_04                     851      /* BMP  */
#define SPR_SCAN2_05                     852      /* BMP  */
#define SPR_SCAN2_06                     853      /* BMP  */
#define SPR_SCAN2_07                     854      /* BMP  */
#define SPR_SCAN2_INV                    855      /* JPEG */
#define SPR_SCAN3_00                     856      /* BMP  */
#define SPR_SCAN3_01                     857      /* BMP  */
#define SPR_SCAN3_02                     858      /* BMP  */
#define SPR_SCAN3_03                     859      /* BMP  */
#define SPR_SCAN3_04                     860      /* BMP  */
#define SPR_SCAN3_05                     861      /* BMP  */
#define SPR_SCAN3_INV                    862      /* JPEG */
#define SPR_SCAN4_00                     863      /* BMP  */
#define SPR_SCAN4_01                     864      /* BMP  */
#define SPR_SCAN4_02                     865      /* BMP  */
#define SPR_SCAN4_03                     866      /* BMP  */
#define SPR_SCAN4_INV                    867      /* JPEG */
#define SPR_SENTINEL                     868      /* JPEG */
#define SPR_SENTRY                       869      /* JPEG */
#define SPR_SHRUB                        870      /* BMP  */
#define SPR_SHRUB_DEAD                   871      /* BMP  */
#define SPR_SHRUB_PIC                    872      /* JPEG */
#define SPR_SHRUVER                      873      /* JPEG */
#define SPR_SHV_ATK                      874      /* BMP  */
#define SPR_SHV_DEAD                     875      /* BMP  */
#define SPR_SHV_EAT1                     876      /* BMP  */
#define SPR_SHV_EAT2                     877      /* BMP  */
#define SPR_SHV_MOV1                     878      /* BMP  */
#define SPR_SHV_MOV2                     879      /* BMP  */
#define SPR_SHV_STILL                    880      /* BMP  */
#define SPR_SICK                         881      /* BMP  */
#define SPR_SIGN_ARENA                   882      /* BMP  */
#define SPR_SIGN_BFC                     883      /* BMP  */
#define SPR_SIGN_FISEC                   884      /* BMP  */
#define SPR_SIGN_JMART                   885      /* BMP  */
#define SPR_SIGN_POLICE                  886      /* BMP  */
#define SPR_SLM_ATK1                     887      /* BMP  */
#define SPR_SLM_ATK2                     888      /* BMP  */
#define SPR_SLM_MOV1                     889      /* BMP  */
#define SPR_SLM_MOV2                     890      /* BMP  */
#define SPR_SLM_MOV3                     891      /* BMP  */
#define SPR_SLM_MOV4                     892      /* BMP  */
#define SPR_SLM_STILL1                   893      /* BMP  */
#define SPR_SLM_STILL2                   894      /* BMP  */
#define SPR_SLM_STILL3                   895      /* BMP  */
#define SPR_SLYMER                       896      /* JPEG */
#define SPR_SNEEKER                      897      /* JPEG */
#define SPR_SNK_ATK1                     898      /* BMP  */
#define SPR_SNK_ATK2                     899      /* BMP  */
#define SPR_SNK_DEAD                     900      /* BMP  */
#define SPR_SNK_MOV1                     901      /* BMP  */
#define SPR_SNK_MOV2                     902      /* BMP  */
#define SPR_SNK_STILL1                   903      /* BMP  */
#define SPR_SNK_STILL2                   904      /* BMP  */
#define SPR_SNK_STILL3                   905      /* BMP  */
#define SPR_SPEAR                        906      /* BMP  */
#define SPR_SPEAR_INV                    907      /* JPEG */
#define SPR_SPLASH                       908      /* JPEG */
#define SPR_SPORES                       909      /* BMP  */
#define SPR_SPORESB                      910      /* BMP  */
#define SPR_SPORESG                      911      /* BMP  */
#define SPR_SPORESR                      912      /* BMP  */
#define SPR_SQR_ATK1                     913      /* BMP  */
#define SPR_SQR_ATK2                     914      /* BMP  */
#define SPR_SQR_MOV1                     915      /* BMP  */
#define SPR_SQR_MOV2                     916      /* BMP  */
#define SPR_SQR_STILL                    917      /* BMP  */
#define SPR_SQU_ATK1                     918      /* BMP  */
#define SPR_SQU_ATK2                     919      /* BMP  */
#define SPR_SQU_DEAD                     920      /* BMP  */
#define SPR_SQU_MOV1                     921      /* BMP  */
#define SPR_SQU_MOV2                     922      /* BMP  */
#define SPR_SQU_STILL1                   923      /* BMP  */
#define SPR_SQU_STILL2                   924      /* BMP  */
#define SPR_SQU_STILL3                   925      /* BMP  */
#define SPR_SQUADSHIP1                   926      /* BMP  */
#define SPR_SQUADSHIP2                   927      /* BMP  */
#define SPR_SQUADSHIPF                   928      /* JPEG */
#define SPR_SQUARGER                     929      /* JPEG */
#define SPR_SQUEEKER                     930      /* JPEG */
#define SPR_STABILIZER0                  931      /* BMP  */
#define SPR_STABILIZER0_INV              932      /* JPEG */
#define SPR_STABILIZER1                  933      /* BMP  */
#define SPR_STABILIZER1_INV              934      /* JPEG */
#define SPR_STABILIZER2                  935      /* BMP  */
#define SPR_STABILIZER2_INV              936      /* JPEG */
#define SPR_STABILIZER3                  937      /* BMP  */
#define SPR_STABILIZER3_INV              938      /* JPEG */
#define SPR_STABILIZER4                  939      /* BMP  */
#define SPR_STABILIZER4_INV              940      /* JPEG */
#define SPR_STALK                        941      /* BMP  */
#define SPR_STALK_CHILL1                 942      /* BMP  */
#define SPR_STALK_CHILL2                 943      /* BMP  */
#define SPR_STALK_DEAD                   944      /* BMP  */
#define SPR_STALK_PIC                    945      /* JPEG */
#define SPR_STALKER                      946      /* JPEG */
#define SPR_STALKPLANT                   947      /* JPEG */
#define SPR_STATAN_INV                   948      /* JPEG */
#define SPR_STEAMEDMUBARK                949      /* BMP  */
#define SPR_STEAMEDMUBARK_INV            950      /* JPEG */
#define SPR_STK_ATK1                     951      /* BMP  */
#define SPR_STK_ATK2                     952      /* BMP  */
#define SPR_STK_ATK3                     953      /* BMP  */
#define SPR_STK_ATK4                     954      /* BMP  */
#define SPR_STK_DEAD                     955      /* BMP  */
#define SPR_STK_EAT1                     956      /* BMP  */
#define SPR_STK_EAT2                     957      /* BMP  */
#define SPR_STK_MOV1                     958      /* BMP  */
#define SPR_STK_MOV2                     959      /* BMP  */
#define SPR_STK_MOV3                     960      /* BMP  */
#define SPR_STK_MOV4                     961      /* BMP  */
#define SPR_STK_STILL                    962      /* BMP  */
#define SPR_STL_ATK                      963      /* BMP  */
#define SPR_STL_DEAD                     964      /* BMP  */
#define SPR_STL_MOV1                     965      /* BMP  */
#define SPR_STL_MOV2                     966      /* BMP  */
#define SPR_STL_STILL                    967      /* BMP  */
#define SPR_STY_ATK                      968      /* BMP  */
#define SPR_STY_DEAD                     969      /* BMP  */
#define SPR_STY_MOV1                     970      /* BMP  */
#define SPR_STY_MOV2                     971      /* BMP  */
#define SPR_STY_STILL                    972      /* BMP  */
#define SPR_SUPERSTIM                    973      /* BMP  */
#define SPR_SUPERSTIM_INV                974      /* JPEG */
#define SPR_SURFACE0                     975      /* JPEG */
#define SPR_SURFACE1                     976      /* JPEG */
#define SPR_SURFACE2                     977      /* JPEG */
#define SPR_SURFACE3                     978      /* JPEG */
#define SPR_SURFACE4                     979      /* JPEG */
#define SPR_SURFACE5                     980      /* JPEG */
#define SPR_SURFACE6                     981      /* JPEG */
#define SPR_SURFACE7                     982      /* JPEG */
#define SPR_SURFACE8                     983      /* JPEG */
#define SPR_SURFACE9                     984      /* JPEG */
#define SPR_SWEAT                        985      /* BMP  */
#define SPR_TELEPORT                     986      /* BMP  */
#define SPR_THR_ATK1                     987      /* BMP  */
#define SPR_THR_ATK2                     988      /* BMP  */
#define SPR_THR_DEAD                     989      /* BMP  */
#define SPR_THR_MOV1                     990      /* BMP  */
#define SPR_THR_MOV2                     991      /* BMP  */
#define SPR_THR_STILL                    992      /* BMP  */
#define SPR_THROBID                      993      /* JPEG */
#define SPR_THRUSTER1_INV                994      /* JPEG */
#define SPR_THRUSTER2_INV                995      /* JPEG */
#define SPR_THRUSTER3_INV                996      /* JPEG */
#define SPR_THRUSTER4_INV                997      /* JPEG */
#define SPR_THRUSTER5_INV                998      /* JPEG */
#define SPR_THRUSTER6_INV                999      /* JPEG */
#define SPR_TIT_ATK1                     1000     /* BMP  */
#define SPR_TIT_ATK2                     1001     /* BMP  */
#define SPR_TIT_ATK3                     1002     /* BMP  */
#define SPR_TIT_ATK4                     1003     /* BMP  */
#define SPR_TIT_DEAD                     1004     /* BMP  */
#define SPR_TIT_MOV1                     1005     /* BMP  */
#define SPR_TIT_MOV2                     1006     /* BMP  */
#define SPR_TIT_MOV3                     1007     /* BMP  */
#define SPR_TIT_MOV4                     1008     /* BMP  */
#define SPR_TIT_STILL1                   1009     /* BMP  */
#define SPR_TIT_STILL2                   1010     /* BMP  */
#define SPR_TIT_STILL3                   1011     /* BMP  */
#define SPR_TIT_STILLB                   1012     /* BMP  */
#define SPR_TITURTILION                  1013     /* JPEG */
#define SPR_TMITG_BELT                   1014     /* BMP  */
#define SPR_TOOTHWORM                    1015     /* JPEG */
#define SPR_TORIX                        1016     /* JPEG */
#define SPR_TOURIST                      1017     /* JPEG */
#define SPR_TOURISTS                     1018     /* BMP  */
#define SPR_TOURISTS_PIC                 1019     /* JPEG */
#define SPR_TOURISTSHIP                  1020     /* BMP  */
#define SPR_TOURISTSHIPF                 1021     /* JPEG */
#define SPR_TRADESHIP                    1022     /* BMP  */
#define SPR_TRADESHIPF                   1023     /* JPEG */
#define SPR_TRAINERGUY00                 1024     /* JPEG */
#define SPR_TRAINERGUY01                 1025     /* JPEG */
#define SPR_TRAINERGUY02                 1026     /* JPEG */
#define SPR_TRAINERGUY03                 1027     /* JPEG */
#define SPR_TRAINERGUY04                 1028     /* JPEG */
#define SPR_TRX_ATKW                     1029     /* BMP  */
#define SPR_TRX_DEAD                     1030     /* BMP  */
#define SPR_TRX_MOV1                     1031     /* BMP  */
#define SPR_TRX_MOV1W                    1032     /* BMP  */
#define SPR_TRX_MOV2                     1033     /* BMP  */
#define SPR_TRX_MOV2W                    1034     /* BMP  */
#define SPR_TRX_STILL                    1035     /* BMP  */
#define SPR_TWM_ATK1                     1036     /* BMP  */
#define SPR_TWM_ATK2                     1037     /* BMP  */
#define SPR_TWM_MOV1                     1038     /* BMP  */
#define SPR_TWM_MOV2                     1039     /* BMP  */
#define SPR_TWM_MOV3                     1040     /* BMP  */
#define SPR_TWM_MOV4                     1041     /* BMP  */
#define SPR_TWM_STILL                    1042     /* BMP  */
#define SPR_UBERWORM                     1043     /* JPEG */
#define SPR_UNLABLEDCAN                  1044     /* BMP  */
#define SPR_UNLABLEDCAN_INV              1045     /* JPEG */
#define SPR_UWM_ATK1                     1046     /* BMP  */
#define SPR_UWM_ATK2                     1047     /* BMP  */
#define SPR_UWM_ATK3                     1048     /* BMP  */
#define SPR_UWM_DEAD                     1049     /* BMP  */
#define SPR_UWM_MOV1                     1050     /* BMP  */
#define SPR_UWM_MOV2                     1051     /* BMP  */
#define SPR_UWM_MOV3                     1052     /* BMP  */
#define SPR_UWM_MOV4                     1053     /* BMP  */
#define SPR_UWM_MOV5                     1054     /* BMP  */
#define SPR_UWM_MOV6                     1055     /* BMP  */
#define SPR_UWM_STILL                    1056     /* BMP  */
#define SPR_VAERIX                       1057     /* JPEG */
#define SPR_VOJODUST                     1058     /* BMP  */
#define SPR_VOJODUST_INV                 1059     /* JPEG */
#define SPR_VRX_ATK1                     1060     /* BMP  */
#define SPR_VRX_ATK2                     1061     /* BMP  */
#define SPR_VRX_ATK3                     1062     /* BMP  */
#define SPR_VRX_MOV1                     1063     /* BMP  */
#define SPR_VRX_MOV2                     1064     /* BMP  */
#define SPR_VRX_MOV3                     1065     /* BMP  */
#define SPR_VRX_STILL1                   1066     /* BMP  */
#define SPR_VRX_STILL2                   1067     /* BMP  */
#define SPR_VRX_STILL3                   1068     /* BMP  */
#define SPR_WAT_DG                       1069     /* BMP  */
#define SPR_WAT_DG_F                     1070     /* BMP  */
#define SPR_WAT_MOV1                     1071     /* BMP  */
#define SPR_WAT_MOV2                     1072     /* BMP  */
#define SPR_WAT_MOV3                     1073     /* BMP  */
#define SPR_WAT_MOV4                     1074     /* BMP  */
#define SPR_WAT_STILL                    1075     /* BMP  */
#define SPR_WATCHERF                     1076     /* JPEG */
#define SPR_WISEOLDGUY00                 1077     /* JPEG */
#define SPR_WISEOLDGUY01                 1078     /* JPEG */
#define SPR_WISEOLDGUY02                 1079     /* JPEG */
#define SPR_WISEOLDGUY03                 1080     /* JPEG */
#define SPR_WISEOLDGUY04                 1081     /* JPEG */
#define SPR_WIZE_GUY1                    1082     /* BMP  */
#define SPR_WIZE_GUY2                    1083     /* BMP  */
#define SPR_WIZE_GUY3                    1084     /* BMP  */
#define SPR_WIZE_GUYF                    1085     /* JPEG */
#define SPR_WORKERF                      1086     /* JPEG */
#define SPR_WORKERM                      1087     /* JPEG */
#define SPR_WRENCH2X_INV                 1088     /* JPEG */
#define SPR_WRENCH_INV                   1089     /* JPEG */
#define SPR_YAZZERT                      1090     /* JPEG */
#define SPR_YELLOWROCK                   1091     /* BMP  */
#define SPR_YELLOWROCK_INV               1092     /* JPEG */
#define SPR_YZT_ATK1                     1093     /* BMP  */
#define SPR_YZT_ATK2                     1094     /* BMP  */
#define SPR_YZT_MOV1                     1095     /* BMP  */
#define SPR_YZT_MOV2                     1096     /* BMP  */
#define SPR_YZT_MOV3                     1097     /* BMP  */
#define SPR_YZT_MOV4                     1098     /* BMP  */
#define SPR_YZT_STILL1                   1099     /* BMP  */
#define SPR_YZT_STILL2                   1100     /* BMP  */
#define SPR_YZT_STILL3                   1101     /* BMP  */
#define SPR_ZOZIN                        1102     /* BMP  */
#define SPR_ZOZIN_INV                    1103     /* JPEG */

#define SPR_COUNT 1104
#define NUM_SURFACES 10

