/* sprite_patch.h generated by trader_strip.pl */

#ifndef _sprite_patch_h
#define _sprite_patch_h 1

#ifdef INV_DEF_MACROS
#  define UP(typ, nam, lvl, sv, jm, cost, common, inv_sprite) {typ, -1, nam, NULL, lvl, sv, -1, -1, 1, -1, -1, -1, jm, cost, common, SPR_ ## inv_sprite, -1, -1, -1, -1, -1, -1, NULL}
#  define CAGE( nam, lvl, sv, jm, cost, common, inv_sprite, lil_sprite) {inv_cage, -1, nam, NULL, lvl, sv, -1, -1, 1, -1, -1, -1, jm, cost, common, SPR_ ## inv_sprite, SPR_ ## lil_sprite,SPR_ ##  lil_sprite ## _BROKEN, -1, -1, -1, -1, NULL}
#  define CLAW( nam, lvl, sv, jm, cost, common, inv_sprite, lil_sprite) {inv_claw_up, -1, nam, NULL, lvl, sv, -1, -1, 1, -1, -1, -1, jm, cost, common, SPR_ ## inv_sprite, SPR_ ## lil_sprite,SPR_ ##  lil_sprite ## _CLOSED, -1, -1, -1, -1, NULL}
#  define HULL( nam, lvl, sv, jm, cost, common, inv_sprite, lil_sprite) {inv_hull_up, -1, nam, NULL, lvl, sv, -1, -1, 1, -1, -1, -1, jm, cost, common, SPR_ ## inv_sprite, SPR_ ## lil_sprite, SPR_ ## lil_sprite, -1, -1, -1, -1, NULL}
#  define AUTO( typ, nam, sv, jm, cost, common, lil_sprite) {typ, -1, nam, NULL, -1, sv, -1, -1, 1, -1, -1, -1, jm, cost, common, SPR_ ## lil_sprite ## _INV, SPR_ ## lil_sprite,-1, -1, -1, -1, -1, NULL}
#  define DEPL( typ, nam, lvl, sv, pow_tox, size, hp, jm, cost, common, inv_sprite, lil_sprite) {typ, -1, nam, NULL, lvl, sv, pow_tox, -1, 1, -1, -1, -1, jm, cost, common, SPR_ ## inv_sprite, -1, -1, -1, -1, -1, -1, NULL}
#  define PROJ( wtyp, nam, dam_sv, tox, drg, grp, rng, vel, relms, jm, cost, common, inv_sprite, projs, hx, hy, ws1, ws2, noise ) {inv_proj, wtyp, nam, NULL, -1, dam_sv, tox, drg, grp, rng, vel, relms, jm, cost, common, SPR_ ## inv_sprite, SPR_ ## ws1, SPR_ ## ws2, SPR_ ## projs, hx, hy, SND_ ## noise, NULL}
#  define THRUST( nam, lvl, fthr_sv, lthr_tox, trate_drg, jm, cost, common, inv_sprite ) {inv_thrust_up, -1, nam, NULL, lvl, fthr_sv, lthr_tox, trate_drg, 1, -1, -1, -1, jm, cost, common, SPR_ ## inv_sprite, -1, -1, -1, -1, -1, -1, NULL}
#endif

typedef enum inv_t {
	inv_none, inv_repair, inv_hint, inv_money, inv_donation,
	inv_claw_up, inv_rope_up, inv_cage_stat_up,
	inv_thrust_up, inv_claw_speed_up, inv_hull_up,
	inv_food, inv_injector, inv_cage, inv_proj, inv_mineral,
	inv_scanner, inv_tower, inv_power, inv_stabilizer, inv_encl
};

typedef struct ivalu_t {
  int typ, wtyp; char *nam, *desc;
  int lvl, sv, tox, drg, grp, rng, vel, relms, jm, cost, common,
      inv_sprite, ws1, ws2, projs, hx, hy, noise;
  struct monst_base *mb_link;
};

void fix_ivalu_desc();


#define IDF_ROPEUP0	ivalu_list[0]
#define IDF_ROPEUP1	ivalu_list[1]
#define IDF_ROPEUP2	ivalu_list[2]
#define IDF_ROPEUP3	ivalu_list[3]
#define IDF_ROPEUP4	ivalu_list[4]


#define IDF_CLAWSPEEDUP0	ivalu_list[5]
#define IDF_CLAWSPEEDUP1	ivalu_list[6]
#define IDF_CLAWSPEEDUP2	ivalu_list[7]
#define IDF_CLAWSPEEDUP3	ivalu_list[8]
#define IDF_CLAWSPEEDUP4	ivalu_list[9]


#define IDF_THRUST0	ivalu_list[10]
#define IDF_THRUST1	ivalu_list[11]
#define IDF_THRUST2	ivalu_list[12]
#define IDF_THRUST3	ivalu_list[13]
#define IDF_THRUST4	ivalu_list[14]
#define IDF_THRUST5	ivalu_list[15]
#define IDF_THRUST6	ivalu_list[16]

#define IDF_CAGESTATUP0	ivalu_list[17]


#define IDF_CAGE0	ivalu_list[18]
#define IDF_CAGE1	ivalu_list[19]
#define IDF_CAGE2	ivalu_list[20]
#define IDF_CAGE3	ivalu_list[21]
#define IDF_CAGE4	ivalu_list[22]
#define IDF_CAGE5	ivalu_list[23]


#define IDF_CLAW0	ivalu_list[24]
#define IDF_CLAW1	ivalu_list[25]
#define IDF_CLAW2	ivalu_list[26]
#define IDF_CLAW3	ivalu_list[27]
#define IDF_CLAW4	ivalu_list[28]


#define IDF_HULL0	ivalu_list[29]
#define IDF_HULL1	ivalu_list[30]
#define IDF_HULL2	ivalu_list[31]
#define IDF_HULL3	ivalu_list[32]
#define IDF_HULL4	ivalu_list[33]
#define IDF_HULL5	ivalu_list[34]




#define IDF_EZSLEEPDARTS	ivalu_list[35]
#define IDF_TRANKQUILDARTS	ivalu_list[36]
#define IDF_PACIFYERDARTS	ivalu_list[37]
#define IDF_OUTCOLDDARTS	ivalu_list[38]
#define IDF_HEARTATTACKDARTS	ivalu_list[39]
#define IDF_COMADARTS	ivalu_list[40]
#define IDF_GORGONDARTS	ivalu_list[41]
#define IDF_RATCHET	ivalu_list[42]
#define IDF_RUMBLER	ivalu_list[43]
#define IDF_LANCER	ivalu_list[44]
#define IDF_MORNINGSTAR	ivalu_list[45]
#define IDF_RAILGUN	ivalu_list[46]
#define IDF_INCINERATOR	ivalu_list[47]
#define IDF_STORMHAND	ivalu_list[48]
#define IDF_PULSAR	ivalu_list[49]
#define IDF_SUNSTRIKER	ivalu_list[50]
#define IDF_PYROCLASTER	ivalu_list[51]
#define IDF_DEATHRAY	ivalu_list[52]


#define IDF_GUNTURRET	ivalu_list[53]
#define IDF_DGTURRET	ivalu_list[54]
#define IDF_XCANNONTURRET	ivalu_list[55]
#define IDF_GALTIXTURRET	ivalu_list[56]

#define IDF_GUNTURRETRAID	ivalu_list[57]
#define IDF_DGTURRETRAID	ivalu_list[58]
#define IDF_XCANNONTURRETRAID	ivalu_list[59]
#define IDF_GALTIXTURRETRAID	ivalu_list[60]

#define IDF_SQUADBLASTER	ivalu_list[61]
#define IDF_WATCHERDG	ivalu_list[62]
#define IDF_ENFORCERXCANNON	ivalu_list[63]
#define IDF_ENFORCERRPG	ivalu_list[64]

#define IDF_ACKATOOSPIT	ivalu_list[65]
#define IDF_MEEKERBLAST	ivalu_list[66]
#define IDF_VRXPSYATTACK	ivalu_list[67]
#define IDF_YZTPSYATTACK	ivalu_list[68]
#define IDF_FIREBALL	ivalu_list[69]
#define IDF_POISONSPORE	ivalu_list[70]
#define IDF_PSYCHOSPORE	ivalu_list[71]
#define IDF_PYROSPORE	ivalu_list[72]
#define IDF_SPEAR	ivalu_list[73]


#define IDF_SOLARARRAY	ivalu_list[74]
#define IDF_FISSIONPLANT	ivalu_list[75]
#define IDF_FUSIONPLANT	ivalu_list[76]

#define IDF_POWERCORE	ivalu_list[77]


#define IDF_RADIOMARKER	ivalu_list[78]
#define IDF_ORGANICSSCANNER	ivalu_list[79]
#define IDF_DELTAWAVESCANNER	ivalu_list[80]
#define IDF_QPARTICLESCANNER	ivalu_list[81]
#define IDF_EPSILONHISCANNER	ivalu_list[82]

#define IDF_GUNTOWER	ivalu_list[83]
#define IDF_DGTOWER	ivalu_list[84]
#define IDF_XCANNONTOWER	ivalu_list[85]
#define IDF_GALTIXTOWER	ivalu_list[86]







#define IDF_CHAINLINKPIN	ivalu_list[87]
#define IDF_CHAINLINKENCLOSURE	ivalu_list[88]
#define IDF_CHAINLINKEXHIBIT	ivalu_list[89]
#define IDF_CHAINLINKGRANDEXHIBIT	ivalu_list[90]
#define IDF_GRATEDPIN	ivalu_list[91]
#define IDF_GRATEDENCLOSURE	ivalu_list[92]
#define IDF_GRATEDEXHIBIT	ivalu_list[93]
#define IDF_GRATEDGRANDEXHIBIT	ivalu_list[94]
#define IDF_SHIELDEDPIN	ivalu_list[95]
#define IDF_SHIELDEDENCLOSURE	ivalu_list[96]
#define IDF_SHIELDEDEXHIBIT	ivalu_list[97]
#define IDF_SHIELDEDGRANDEXHIBIT	ivalu_list[98]



#define IDF_JUMPGATENODE	ivalu_list[99]
#define IDF_JUMPGATESTABILIZER	ivalu_list[100]
#define IDF_TRANSPHASITESTABILIZER	ivalu_list[101]
#define IDF_MULTIPHASITESTABILIZER	ivalu_list[102]
#define IDF_OMNIPHASITESTABILIZER	ivalu_list[103]


#define IDF_RAIDERGUNTOWER	ivalu_list[104]
#define IDF_RAIDERDGTOWER	ivalu_list[105]
#define IDF_RAIDERXCANNONTOWER	ivalu_list[106]
#define IDF_RAIDERGALTIXTOWER	ivalu_list[107]

#define IDF_RAIDERSOLARARRAY	ivalu_list[108]
#define IDF_RAIDERFISSIONPLANT	ivalu_list[109]
#define IDF_RAIDERFUSIONPLANT	ivalu_list[110]

#define IDF_MIXEDVEGETABLES	ivalu_list[111]
#define IDF_EYESTALKSHOOTS	ivalu_list[112]
#define IDF_CANNEDFURBIT	ivalu_list[113]
#define IDF_STEAMEDMUBARK	ivalu_list[114]
#define IDF_UNLABELEDCAN	ivalu_list[115]
#define IDF_MARJACOLA	ivalu_list[116]
#define IDF_IHB77	ivalu_list[117]
#define IDF_VOJODUST	ivalu_list[118]
#define IDF_ZOZIN	ivalu_list[119]
#define IDF_LYKEDOFAN	ivalu_list[120]
#define IDF_FRIEDCHICKEN	ivalu_list[121]


#define IDF_DETOX	ivalu_list[122]
#define IDF_ROZOLIN	ivalu_list[123]
#define IDF_GLOWINGLIQUID	ivalu_list[124]
#define IDF_SUPERSTIM	ivalu_list[125]
#define IDF_JR19AZF	ivalu_list[126]
#define IDF_AISORMBA	ivalu_list[127]
#define IDF_NANOBOTS	ivalu_list[128]
#define IDF_HX12	ivalu_list[129]
#define IDF_MORODULB	ivalu_list[130]
#define IDF_PROJECT17	ivalu_list[131]

#define IDF_REDROCK	ivalu_list[132]
#define IDF_YELLOWROCK	ivalu_list[133]
#define IDF_PURPLEROCK	ivalu_list[134]
#define IDF_GREENCRYSTALS	ivalu_list[135]
#define IDF_BIOCITE	ivalu_list[136]
#define IDF_MONEY	ivalu_list[137]


#define IDF_REPAIR99	ivalu_list[138]
#define IDF_REPAIR98	ivalu_list[139]
#define IDF_REPAIR0	ivalu_list[140]
#define IDF_REPAIR1	ivalu_list[141]
#define IDF_REPAIR2	ivalu_list[142]
#define IDF_REPAIR3	ivalu_list[143]
#define IDF_REPAIR4	ivalu_list[144]
#define IDF_REPAIR5	ivalu_list[145]
#define IDF_REPAIR6	ivalu_list[146]
#define IDF_REPAIR7	ivalu_list[147]
#define IDF_REPAIR8	ivalu_list[148]
#define IDF_REPAIR9	ivalu_list[149]
#define IDF_REPAIR10	ivalu_list[150]
#define IDF_REPAIR11	ivalu_list[151]

#define IDF_HINT1	ivalu_list[152]
#define IDF_HINT2	ivalu_list[153]

#define IDF_DONATION1	ivalu_list[154]




#define FIRST_INV_CAGE_IDX 18
#define FIRST_INV_CAGE_STAT_UP_IDX 17
#define FIRST_INV_CLAW_SPEED_UP_IDX 5
#define FIRST_INV_DONATION_IDX 154
#define FIRST_INV_FOOD_IDX 111
#define FIRST_INV_HINT_IDX 152
#define FIRST_INV_HULL_IDX 29
#define FIRST_INV_INJECTOR_IDX 122
#define FIRST_INV_MINERAL_IDX 132
#define FIRST_INV_MONEY_IDX 137
#define FIRST_INV_REPAIR_IDX 138
#define FIRST_INV_ROPE_UP_IDX 0

#define NUM_INV_CAGE 6
#define NUM_INV_CAGE_STAT_UP 1
#define NUM_INV_CLAW_SPEED_UP 5
#define NUM_INV_DONATION 1
#define NUM_INV_ENCL 12
#define NUM_INV_FOOD 11
#define NUM_INV_HINT 2
#define NUM_INV_HULL 6
#define NUM_INV_INJECTOR 10
#define NUM_INV_MINERAL 5
#define NUM_INV_MONEY 1
#define NUM_INV_POWER 7
#define NUM_INV_REPAIR 14
#define NUM_INV_ROPE_UP 5
#define NUM_INV_SCANNER 5
#define NUM_INV_STABILIZER 5
#define NUM_INV_TOWER 8
#define NUM_IVALU_LIST 155

#define SPR_DEBRIES SPR_NO_LIL_PIC
#define SPR_FRIEDCHICKEN SPR_NO_LIL_PIC
#define SPR_MIXEDVEGETABLES SPR_NO_LIL_PIC
#define SPR_MIXEDVEGETABLES_INV SPR_NO_BIG_PIC
#define SPR_MONEY_INV_INV SPR_NO_BIG_PIC
#define SPR_NONE SPR_NO_LIL_PIC
#define SPR_P_GUN_F SPR_NO_LIL_PIC
#define SPR_UNLABELEDCAN SPR_NO_LIL_PIC
#define SPR_UNLABELEDCAN_INV SPR_NO_BIG_PIC
#define SPR_big SPR_NO_LIL_PIC
#define SPR_top SPR_NO_LIL_PIC
#define SPR_x SPR_NO_LIL_PIC
extern ivalu_t ivalu_list[NUM_IVALU_LIST];
#define AST_LIST_ITEMS {SPR_AA0001, SPR_AB0001, SPR_AC0001, SPR_AD0001, SPR_AE0001, SPR_AF0001, SPR_AG0001, SPR_AH0001, SPR_AI0001, SPR_AJ0001}
#endif
