/* generated by trader_strip.pl (do not hand edit.) */

extern monst_base 
	mb_fern,
	mb_shrub,
	mb_stalkplant,
	mb_happytree,
	mb_mimmack,
	mb_quiver,
	mb_poisonshroom,
	mb_psychoshroom,
	mb_pyroshroom,
	mb_roachy,
	mb_krulasite,
	mb_quitofly,
	mb_pygment,
	mb_frogert,
	mb_furbit,
	mb_shruver,
	mb_radrunner,
	mb_mubark,
	mb_molber,
	mb_ackatoo,
	mb_squeeker,
	mb_meeker,
	mb_sneeker,
	mb_vaerix,
	mb_yazzert,
	mb_malcumbit,
	mb_squarger,
	mb_slymer,
	mb_bervul,
	mb_rexrex,
	mb_throbid,
	mb_toothworm,
	mb_orick,
	mb_cheech,
	mb_hoveler,
	mb_stalker,
	mb_crysillian,
	mb_drexler,
	mb_krakin,
	mb_dragoonigon,
	mb_mamothquito,
	mb_uberworm,
	mb_bigasaurus,
	mb_titurtilion,
	mb_golgithan,
	mb_netship,
	mb_astbase,
	mb_raidship,
	mb_raider,
	mb_raidercamp,
	mb_sentry,
	mb_sentinel,
	mb_squadship,
	mb_watcher,
	mb_enforcer,
	mb_policestation,
	mb_cityblda,
	mb_citybldb,
	mb_worker,
	mb_hippie,
	mb_trainer,
	mb_merchant,
	mb_tourist,
	mb_hunter,
	mb_jmart,
	mb_bfc,
	mb_arena,
	mb_fisec,
	mb_wisehut,
	mb_orickcamp,
	mb_orickcampfire,
	mb_crysillianruins,
	mb_crashsite,
	mb_ufo,
	mb_hole,
	mb_meteor,
	mb_cage0,
	mb_cage1,
	mb_cage2,
	mb_cage3,
	mb_cage4,
	mb_cage5,
	mb_ezsleepdarts,
	mb_trankquildarts,
	mb_pacifyerdarts,
	mb_outcolddarts,
	mb_heartattackdarts,
	mb_comadarts,
	mb_gorgondarts,
	mb_ratchet,
	mb_rumbler,
	mb_lancer,
	mb_morningstar,
	mb_railgun,
	mb_incinerator,
	mb_stormhand,
	mb_pulsar,
	mb_sunstriker,
	mb_pyroclaster,
	mb_deathray,
	mb_gunturret,
	mb_dgturret,
	mb_xcannonturret,
	mb_galtixturret,
	mb_gunturretraid,
	mb_dgturretraid,
	mb_xcannonturretraid,
	mb_galtixturretraid,
	mb_squadblaster,
	mb_watcherdg,
	mb_enforcerxcannon,
	mb_enforcerrpg,
	mb_ackatoospit,
	mb_meekerblast,
	mb_vrxpsyattack,
	mb_yztpsyattack,
	mb_fireball,
	mb_poisonspore,
	mb_psychospore,
	mb_pyrospore,
	mb_spear,
	mb_solararray,
	mb_fissionplant,
	mb_fusionplant,
	mb_powercore,
	mb_radiomarker,
	mb_organicsscanner,
	mb_deltawavescanner,
	mb_qparticlescanner,
	mb_epsilonhiscanner,
	mb_guntower,
	mb_dgtower,
	mb_xcannontower,
	mb_galtixtower,
	mb_chainlinkpin,
	mb_chainlinkenclosure,
	mb_chainlinkexhibit,
	mb_chainlinkgrandexhibit,
	mb_gratedpin,
	mb_gratedenclosure,
	mb_gratedexhibit,
	mb_gratedgrandexhibit,
	mb_shieldedpin,
	mb_shieldedenclosure,
	mb_shieldedexhibit,
	mb_shieldedgrandexhibit,
	mb_jumpgatenode,
	mb_jumpgatestabilizer,
	mb_transphasitestabilizer,
	mb_multiphasitestabilizer,
	mb_omniphasitestabilizer,
	mb_raiderguntower,
	mb_raiderdgtower,
	mb_raiderxcannontower,
	mb_raidergaltixtower,
	mb_raidersolararray,
	mb_raiderfissionplant,
	mb_raiderfusionplant,
	mb_mixedvegetables,
	mb_eyestalkshoots,
	mb_cannedfurbit,
	mb_steamedmubark,
	mb_unlabeledcan,
	mb_marjacola,
	mb_ihb77,
	mb_vojodust,
	mb_zozin,
	mb_lykedofan,
	mb_friedchicken,
	mb_detox,
	mb_rozolin,
	mb_glowingliquid,
	mb_superstim,
	mb_jr19azf,
	mb_aisormba,
	mb_nanobots,
	mb_hx12,
	mb_morodulb,
	mb_project17,
	mb_redrock,
	mb_yellowrock,
	mb_purplerock,
	mb_greencrystals,
	mb_biocite,
	mb_money,
    dumby_monster_base;

#ifndef IN_MONSTBASE_CC
   extern monst_base *mb_list_all[], *mb_list_eatable[], *mb_list_attackable[];
#else
monst_base *mb_list_all[] = {
	&mb_fern,
	&mb_shrub,
	&mb_stalkplant,
	&mb_happytree,
	&mb_mimmack,
	&mb_quiver,
	&mb_poisonshroom,
	&mb_psychoshroom,
	&mb_pyroshroom,
	&mb_roachy,
	&mb_krulasite,
	&mb_quitofly,
	&mb_pygment,
	&mb_frogert,
	&mb_furbit,
	&mb_shruver,
	&mb_radrunner,
	&mb_mubark,
	&mb_molber,
	&mb_ackatoo,
	&mb_squeeker,
	&mb_meeker,
	&mb_sneeker,
	&mb_vaerix,
	&mb_yazzert,
	&mb_malcumbit,
	&mb_squarger,
	&mb_slymer,
	&mb_bervul,
	&mb_rexrex,
	&mb_throbid,
	&mb_toothworm,
	&mb_orick,
	&mb_cheech,
	&mb_hoveler,
	&mb_stalker,
	&mb_crysillian,
	&mb_drexler,
	&mb_krakin,
	&mb_dragoonigon,
	&mb_mamothquito,
	&mb_uberworm,
	&mb_bigasaurus,
	&mb_titurtilion,
	&mb_golgithan,
	&mb_netship,
	&mb_astbase,
	&mb_raidship,
	&mb_raider,
	&mb_raidercamp,
	&mb_sentry,
	&mb_sentinel,
	&mb_squadship,
	&mb_watcher,
	&mb_enforcer,
	&mb_policestation,
	&mb_cityblda,
	&mb_citybldb,
	&mb_worker,
	&mb_hippie,
	&mb_trainer,
	&mb_merchant,
	&mb_tourist,
	&mb_hunter,
	&mb_jmart,
	&mb_bfc,
	&mb_arena,
	&mb_fisec,
	&mb_wisehut,
	&mb_orickcamp,
	&mb_orickcampfire,
	&mb_crysillianruins,
	&mb_crashsite,
	&mb_ufo,
	&mb_hole,
	&mb_meteor,
	&mb_cage0,
	&mb_cage1,
	&mb_cage2,
	&mb_cage3,
	&mb_cage4,
	&mb_cage5,
	&mb_ezsleepdarts,
	&mb_trankquildarts,
	&mb_pacifyerdarts,
	&mb_outcolddarts,
	&mb_heartattackdarts,
	&mb_comadarts,
	&mb_gorgondarts,
	&mb_ratchet,
	&mb_rumbler,
	&mb_lancer,
	&mb_morningstar,
	&mb_railgun,
	&mb_incinerator,
	&mb_stormhand,
	&mb_pulsar,
	&mb_sunstriker,
	&mb_pyroclaster,
	&mb_deathray,
	&mb_gunturret,
	&mb_dgturret,
	&mb_xcannonturret,
	&mb_galtixturret,
	&mb_gunturretraid,
	&mb_dgturretraid,
	&mb_xcannonturretraid,
	&mb_galtixturretraid,
	&mb_squadblaster,
	&mb_watcherdg,
	&mb_enforcerxcannon,
	&mb_enforcerrpg,
	&mb_ackatoospit,
	&mb_meekerblast,
	&mb_vrxpsyattack,
	&mb_yztpsyattack,
	&mb_fireball,
	&mb_poisonspore,
	&mb_psychospore,
	&mb_pyrospore,
	&mb_spear,
	&mb_solararray,
	&mb_fissionplant,
	&mb_fusionplant,
	&mb_powercore,
	&mb_radiomarker,
	&mb_organicsscanner,
	&mb_deltawavescanner,
	&mb_qparticlescanner,
	&mb_epsilonhiscanner,
	&mb_guntower,
	&mb_dgtower,
	&mb_xcannontower,
	&mb_galtixtower,
	&mb_chainlinkpin,
	&mb_chainlinkenclosure,
	&mb_chainlinkexhibit,
	&mb_chainlinkgrandexhibit,
	&mb_gratedpin,
	&mb_gratedenclosure,
	&mb_gratedexhibit,
	&mb_gratedgrandexhibit,
	&mb_shieldedpin,
	&mb_shieldedenclosure,
	&mb_shieldedexhibit,
	&mb_shieldedgrandexhibit,
	&mb_jumpgatenode,
	&mb_jumpgatestabilizer,
	&mb_transphasitestabilizer,
	&mb_multiphasitestabilizer,
	&mb_omniphasitestabilizer,
	&mb_raiderguntower,
	&mb_raiderdgtower,
	&mb_raiderxcannontower,
	&mb_raidergaltixtower,
	&mb_raidersolararray,
	&mb_raiderfissionplant,
	&mb_raiderfusionplant,
	&mb_mixedvegetables,
	&mb_eyestalkshoots,
	&mb_cannedfurbit,
	&mb_steamedmubark,
	&mb_unlabeledcan,
	&mb_marjacola,
	&mb_ihb77,
	&mb_vojodust,
	&mb_zozin,
	&mb_lykedofan,
	&mb_friedchicken,
	&mb_detox,
	&mb_rozolin,
	&mb_glowingliquid,
	&mb_superstim,
	&mb_jr19azf,
	&mb_aisormba,
	&mb_nanobots,
	&mb_hx12,
	&mb_morodulb,
	&mb_project17,
	&mb_redrock,
	&mb_yellowrock,
	&mb_purplerock,
	&mb_greencrystals,
	&mb_biocite,
	&mb_money,
	NULL
};

monst_base *mb_list_eatable[] = {
    NULL
};

monst_base *mb_list_attackable[] = {
    NULL
};

monst_base dumby_monster_base;

#endif
#define FOR_EACH_SPAWN_NUM \
	SPAWN_NUM(fern) \
	SPAWN_NUM(shrub) \
	SPAWN_NUM(stalkplant) \
	SPAWN_NUM(happytree) \
	SPAWN_NUM(mimmack) \
	SPAWN_NUM(quiver) \
	SPAWN_NUM(poisonshroom) \
	SPAWN_NUM(psychoshroom) \
	SPAWN_NUM(pyroshroom) \
	SPAWN_NUM(roachy) \
	SPAWN_NUM(krulasite) \
	SPAWN_NUM(quitofly) \
	SPAWN_NUM(pygment) \
	SPAWN_NUM(frogert) \
	SPAWN_NUM(furbit) \
	SPAWN_NUM(shruver) \
	SPAWN_NUM(radrunner) \
	SPAWN_NUM(mubark) \
	SPAWN_NUM(molber) \
	SPAWN_NUM(ackatoo) \
	SPAWN_NUM(squeeker) \
	SPAWN_NUM(meeker) \
	SPAWN_NUM(sneeker) \
	SPAWN_NUM(vaerix) \
	SPAWN_NUM(yazzert) \
	SPAWN_NUM(malcumbit) \
	SPAWN_NUM(squarger) \
	SPAWN_NUM(slymer) \
	SPAWN_NUM(bervul) \
	SPAWN_NUM(rexrex) \
	SPAWN_NUM(throbid) \
	SPAWN_NUM(toothworm) \
	SPAWN_NUM(orick) \
	SPAWN_NUM(cheech) \
	SPAWN_NUM(hoveler) \
	SPAWN_NUM(stalker) \
	SPAWN_NUM(crysillian) \
	SPAWN_NUM(drexler) \
	SPAWN_NUM(krakin) \
	SPAWN_NUM(dragoonigon) \
	SPAWN_NUM(mamothquito) \
	SPAWN_NUM(uberworm) \
	SPAWN_NUM(bigasaurus) \
	SPAWN_NUM(titurtilion) \
	SPAWN_NUM(golgithan) \
	SPAWN_NUM(netship) \
	SPAWN_NUM(astbase) \
	SPAWN_NUM(raidship) \
	SPAWN_NUM(raider) \
	SPAWN_NUM(raidercamp) \
	SPAWN_NUM(sentry) \
	SPAWN_NUM(sentinel) \
	SPAWN_NUM(squadship) \
	SPAWN_NUM(watcher) \
	SPAWN_NUM(enforcer) \
	SPAWN_NUM(policestation) \
	SPAWN_NUM(cityblda) \
	SPAWN_NUM(citybldb) \
	SPAWN_NUM(worker) \
	SPAWN_NUM(hippie) \
	SPAWN_NUM(trainer) \
	SPAWN_NUM(merchant) \
	SPAWN_NUM(tourist) \
	SPAWN_NUM(hunter) \
	SPAWN_NUM(jmart) \
	SPAWN_NUM(bfc) \
	SPAWN_NUM(arena) \
	SPAWN_NUM(fisec) \
	SPAWN_NUM(wisehut) \
	SPAWN_NUM(orickcamp) \
	SPAWN_NUM(orickcampfire) \
	SPAWN_NUM(crysillianruins) \
	SPAWN_NUM(crashsite) \
	SPAWN_NUM(ufo) \
	SPAWN_NUM(hole) \
	SPAWN_NUM(meteor) \
/* MACRO END */

/* EOF. */
