/* Allegro datafile object indexes, produced by dat v4.1.18 (WIP), MinGW32.s */
/* Datafile: sounds.dat */
/* Date: Wed Jun 08 04:25:57 2005 */
/* Do not hand edit! */

#define SND_BFCCANITAKE              0        /* OGG  */
#define SND_BFCENJOYYOURMEAL         1        /* OGG  */
#define SND_BFCFREEZER               2        /* OGG  */
#define SND_BFCGOODHOME              3        /* OGG  */
#define SND_BFCHAVEANICEDAY          4        /* OGG  */
#define SND_BFCHOPEITTASTES          5        /* OGG  */
#define SND_BFCINSUFFFUNDS           6        /* OGG  */
#define SND_BFCMONSTERSIZE           7        /* OGG  */
#define SND_BFCNEEDCAGE              8        /* OGG  */
#define SND_BFCPETS                  9        /* OGG  */
#define SND_BFCRETURNPOL             10       /* OGG  */
#define SND_BFCTENMINUTE             11       /* OGG  */
#define SND_BFCUMM                   12       /* OGG  */
#define SND_BFCWELCOME               13       /* OGG  */
#define SND_BIG_BRK                  14       /* OGG  */
#define SND_BIG_DIE                  15       /* OGG  */
#define SND_BIG_EAT                  16       /* OGG  */
#define SND_BIG_HRT                  17       /* OGG  */
#define SND_BRV_BRK                  18       /* OGG  */
#define SND_BUG_BRK                  19       /* OGG  */
#define SND_BUG_DIE                  20       /* OGG  */
#define SND_BUG_EAT                  21       /* OGG  */
#define SND_BUILD                    22       /* OGG  */
#define SND_CCH_BRK                  23       /* OGG  */
#define SND_CHACHING                 24       /* OGG  */
#define SND_COH_DIE                  25       /* OGG  */
#define SND_COH_FRK                  26       /* OGG  */
#define SND_COH_HRT                  27       /* OGG  */
#define SND_CRY_DIE                  28       /* OGG  */
#define SND_CRY_HRT                  29       /* OGG  */
#define SND_DRA_BRK                  30       /* OGG  */
#define SND_EEK_DIE                  31       /* OGG  */
#define SND_EEK_HRT                  32       /* OGG  */
#define SND_FAL_DIE                  33       /* OGG  */
#define SND_FIRE_AKTSPIT             34       /* OGG  */
#define SND_FIRE_CLAW                35       /* OGG  */
#define SND_FIRE_DEATHRAY            36       /* OGG  */
#define SND_FIRE_DGCANNON            37       /* OGG  */
#define SND_FIRE_DRAG                38       /* OGG  */
#define SND_FIRE_ENFCANNON           39       /* OGG  */
#define SND_FIRE_ENFROCKET           40       /* OGG  */
#define SND_FIRE_GALTIX              41       /* OGG  */
#define SND_FIRE_GUNCANNON           42       /* OGG  */
#define SND_FIRE_INCENERATOR         43       /* OGG  */
#define SND_FIRE_LANCER              44       /* OGG  */
#define SND_FIRE_MEEKBLAST           45       /* OGG  */
#define SND_FIRE_MORNINGSTAR         46       /* OGG  */
#define SND_FIRE_PSY                 47       /* OGG  */
#define SND_FIRE_PULSAR              48       /* OGG  */
#define SND_FIRE_PYROCLASTER         49       /* OGG  */
#define SND_FIRE_RACHET              50       /* OGG  */
#define SND_FIRE_RAILGUN             51       /* OGG  */
#define SND_FIRE_RUMBLER             52       /* OGG  */
#define SND_FIRE_SPORE               53       /* OGG  */
#define SND_FIRE_SQUADBLAST          54       /* OGG  */
#define SND_FIRE_STORMHAND           55       /* OGG  */
#define SND_FIRE_SUNSTRIKER          56       /* OGG  */
#define SND_FIRE_WATCANNON           57       /* OGG  */
#define SND_FIRE_XCANNON             58       /* OGG  */
#define SND_FISAQUIREOK              59       /* OGG  */
#define SND_FISBYE                   60       /* OGG  */
#define SND_FISERRERRERR             61       /* OGG  */
#define SND_FISERRFUNDS              62       /* OGG  */
#define SND_FISERRSPACE              63       /* OGG  */
#define SND_FISERRSTOCK              64       /* OGG  */
#define SND_FISORDEROK               65       /* OGG  */
#define SND_FISWELCOME               66       /* OGG  */
#define SND_FRG_BRK                  67       /* OGG  */
#define SND_GAMEOVER                 68       /* OGG  */
#define SND_GIB_JMART00              69       /* OGG  */
#define SND_GIB_JMART01              70       /* OGG  */
#define SND_GIB_JMART02              71       /* OGG  */
#define SND_GIB_JMART03              72       /* OGG  */
#define SND_GIB_PITGUY               73       /* OGG  */
#define SND_GIB_PRREP                74       /* OGG  */
#define SND_GIB_TRAINER              75       /* OGG  */
#define SND_GIB_WIZE                 76       /* OGG  */
#define SND_GOL_BRK                  77       /* OGG  */
#define SND_HEALING                  78       /* OGG  */
#define SND_HIP_BRK                  79       /* OGG  */
#define SND_HOOK_CLAW                80       /* OGG  */
#define SND_HOV_BRK                  81       /* OGG  */
#define SND_HRB_EAT                  82       /* OGG  */
#define SND_INCOMMING                83       /* OGG  */
#define SND_KRK_BRK                  84       /* OGG  */
#define SND_KRK_HRT                  85       /* OGG  */
#define SND_MAL_BRK                  86       /* OGG  */
#define SND_MAN_DIE                  87       /* OGG  */
#define SND_MAN_FRK                  88       /* OGG  */
#define SND_MAN_HRT                  89       /* OGG  */
#define SND_MBK_BRK                  90       /* OGG  */
#define SND_MBK_DIE                  91       /* OGG  */
#define SND_MBK_HRT                  92       /* OGG  */
#define SND_MED_DIE                  93       /* OGG  */
#define SND_MED_EAT                  94       /* OGG  */
#define SND_MEK_BRK                  95       /* OGG  */
#define SND_MERADDTOLAND             96       /* OGG  */
#define SND_MERADDTOSHIP             97       /* OGG  */
#define SND_MERBECAREFUL             98       /* OGG  */
#define SND_MERCAGEFORTHAT           99       /* OGG  */
#define SND_MERDONTKILLYOU           100      /* OGG  */
#define SND_MERDONTPAYME             101      /* OGG  */
#define SND_MERENJOYNEWGOODS         102      /* OGG  */
#define SND_MERGREETFR               103      /* OGG  */
#define SND_MERGREETNUT              104      /* OGG  */
#define SND_MERGREETUN               105      /* OGG  */
#define SND_MERNOWARENTY             106      /* OGG  */
#define SND_MERPULLPROF              107      /* OGG  */
#define SND_MERSELLMENU              108      /* OGG  */
#define SND_MERSETTLEFOR             109      /* OGG  */
#define SND_MERSHOWIHAVE             110      /* OGG  */
#define SND_MERUNTILNEXTTIME         111      /* OGG  */
#define SND_MERYOUFOOL               112      /* OGG  */
#define SND_MISS_CLAW                113      /* OGG  */
#define SND_MMQ_BRK                  114      /* OGG  */
#define SND_MOL_BRK                  115      /* OGG  */
#define SND_ORIBYE                   116      /* OGG  */
#define SND_ORIHAPPYGREET            117      /* OGG  */
#define SND_ORIMELIKES               118      /* OGG  */
#define SND_ORIMELIKESALOT           119      /* OGG  */
#define SND_ORINORMGREET             120      /* OGG  */
#define SND_POLGOTNUTS               121      /* OGG  */
#define SND_POLHELLOCITIZEN          122      /* OGG  */
#define SND_POLNOCASH                123      /* OGG  */
#define SND_POLOHITSYOU              124      /* OGG  */
#define SND_POLRIGHTSIDEOFLAW        125      /* OGG  */
#define SND_POLSTAYOUTOFTROUBLE      126      /* OGG  */
#define SND_POLTRANSACTION           127      /* OGG  */
#define SND_QTF_BRK                  128      /* OGG  */
#define SND_RAR_BRK                  129      /* OGG  */
#define SND_RAR_HRT                  130      /* OGG  */
#define SND_RAT_BRK                  131      /* OGG  */
#define SND_RAT_HRT                  132      /* OGG  */
#define SND_RATTLECAGE               133      /* OGG  */
#define SND_REP_DIE                  134      /* OGG  */
#define SND_REP_HRT                  135      /* OGG  */
#define SND_RESPAWN                  136      /* OGG  */
#define SND_RRX_BRK                  137      /* OGG  */
#define SND_RRX_HRT                  138      /* OGG  */
#define SND_SLM_BRK                  139      /* OGG  */
#define SND_SLM_DIE                  140      /* OGG  */
#define SND_SMASHCAGE                141      /* OGG  */
#define SND_SML_DIE                  142      /* OGG  */
#define SND_SML_EAT                  143      /* OGG  */
#define SND_SNK_BRK                  144      /* OGG  */
#define SND_SQR_BRK                  145      /* OGG  */
#define SND_SQU_BRK                  146      /* OGG  */
#define SND_THR_BRK                  147      /* OGG  */
#define SND_TOSS_DART                148      /* OGG  */
#define SND_TOSS_SPEAR               149      /* OGG  */
#define SND_UWM_BRK                  150      /* OGG  */
#define SND_WARPIN                   151      /* OGG  */


#define SND_COUNT 152
